var cav_list = 
[
{'simpleName':'4G','fullName':'the 4th Generation mobile communication technology','description':'第四代移动通信技术'},
{'simpleName':'5G','fullName':'the 5th Generation mobile communication technology','description':'第五代移动通信技术'},
{'simpleName':'5GNR','fullName':'5G New Radio','description':'基于OFDM的全新空口设计的全球性5G标准'},
{'simpleName':'ABS','fullName':'Anti-lock Braking System','description':'制动防抱死系统'},
{'simpleName':'ACL','fullName':'Access Control List','description':'访问控制列表'},
{'simpleName':'AD','fullName':'Autonomous Driving','description':'自动驾驶'},
{'simpleName':'ADAS','fullName':'Advanced Driver Assistance Systems','description':'高级驾驶辅助系统'},
{'simpleName':'ADS','fullName':'Application Data-Exchange Service','description':'应用数据交换服务'},
{'simpleName':'AID','fullName':'Application Identification','description':'应用标识'},
{'simpleName':'API','fullName':'Application Programming Interface','description':'应用程序编程接口'},
{'simpleName':'ASN.1','fullName':'Abstract Syntax Notation One','description':'抽象语法记法'},
{'simpleName':'AVW','fullName':'Abnormal Vehicle Warning','description':'异常车辆提醒'},
{'simpleName':'ASIL','fullName':'Automotive Safety Integrity Level','description':'汽车安全完整性等级'},
{'simpleName':'BSM','fullName':'Basic Safety Message','description':'基本安全消息'},
{'simpleName':'BSW','fullName':'Blind Spot Warning','description':'盲区预警'},
{'simpleName':'BSW-LCW','fullName':'Blind Spot Warning-Lane Change Warning','description':'盲区预警-变道辅助'},
{'simpleName':'CA','fullName':'Certification Authority','description':'认证机构的国际通称，是指对数字证书的申请者发放、管理、取消数字证书的机构'},
{'simpleName':'CACC','fullName':'Cooperative Adaptive Cruise Control','description':'协作式自适应巡航'},
{'simpleName':'CAN','fullName':'Controller Area Network','description':'控制器局域网络'},
{'simpleName':'CAV','fullName':'Collision Avoidance Range','description':'防撞距离'},
{'simpleName':'CAV','fullName':'Connected and Automated Vehicle','description':'智能网联汽车'},
{'simpleName':'CBR','fullName':'Chanel Busy Ratio','description':'信道繁忙率'},
{'simpleName':'CDN','fullName':'Content Distribution Network','description':'内容分发网络'},
{'simpleName':'CHPVP','fullName':'Cooperative High Priority Vehicle Passing','description':'协作式优先车辆通行'},
{'simpleName':'CIP','fullName':'Cooperative Intersection Passing','description':'协作式交叉口通行'},
{'simpleName':'C-ITS','fullName':'China ITS Industry Alliance','description':'中国智能交通产业联盟'},
{'simpleName':'CLC','fullName':'Cooperative Lane Change','description':'协作式变道'},
{'simpleName':'CLPMM','fullName':'Connectionless Platooning Management Message','description':'编队管理消息'},
{'simpleName':'CLW','fullName':'Control Lost Warning','description':'车辆失控预警'},
{'simpleName':'CPM','fullName':'Cooperative Platooning Management','description':'协作式车辆编队管理'},
{'simpleName':'CSAE','fullName':'Society of Automotive Engineers of China','description':'中国汽车工程学会'},
{'simpleName':'C-V2X','fullName':'Cellular-V2X','description':'蜂窝车联网'},
{'simpleName':'CVM','fullName':'Cooperative Vehicle Merge','description':'协作式车辆汇入'},
{'simpleName':'DDS','fullName':'Differential Data Service','description':'差分数据服务'},
{'simpleName':'DE','fullName':'Data Element','description':'数据元素'},
{'simpleName':'DF','fullName':'Data Frame','description':'数据帧'},
{'simpleName':'DLM','fullName':'Dynamic Lane Management','description':'动态车道管理'},
{'simpleName':'DME','fullName':'DSRC Management Entity','description':'专用短程通信管理实体'},
{'simpleName':'DNPW','fullName':'Do Not Pass Warning','description':'逆向超车预警'},
{'simpleName':'DSM','fullName':'DSRC Short Message','description':'专用短程通信短消息'},
{'simpleName':'DSMP','fullName':'Dedicated Short MessageProtocol','description':'专用短程通信短消息协议'},
{'simpleName':'DSRC','fullName':'Dedicated Short Range Communications','description':'专用短程通信'},
{'simpleName':'DTC','fullName':'Distance To Collision','description':'碰撞距离'},
{'simpleName':'DTI','fullName':'Distance-to-Intersection','description':'到交叉口的距离'},
{'simpleName':'EBW','fullName':'Emergency Brake Warning','description':'紧急制动预警'},
{'simpleName':'ETC','fullName':'Electronic Toll Collection','description':'电子不停车收费系统'},
{'simpleName':'ETH','fullName':'ethernet','description':'以太网接口'},
{'simpleName':'ETSI','fullName':'European Telecommunications Standards Institute','description':'欧洲电信标准化协会'},
{'simpleName':'EV','fullName':'Equipped Vehicle','description':'装载通信系统的车辆'},
{'simpleName':'EVW','fullName':'Emergency Vehicle Warning','description':'紧急车辆提醒'},
{'simpleName':'FCW','fullName':'Forward Collision Warning','description':'前向碰撞预警'},
{'simpleName':'FDDLTE','fullName':'Frequency Division Duplexing LTE','description':'频分双工LTE'},
{'simpleName':'GB','fullName':'Guo Biao (Nation Standard)','description':'中国国家标准'},
{'simpleName':'GLOSA','fullName':'Green Light Optimal Speed Advisory','description':'绿波车速引导'},
{'simpleName':'GNSS','fullName':'Global Navigation Satellite System','description':'全球导航卫星系统'},
{'simpleName':'GSPA','fullName':'Guidance Service in Parking Area','description':'场站路径引导服务'},
{'simpleName':'HDMI','fullName':'High Definition Multimedia Interface','description':'高清晰度多媒体接口'},
{'simpleName':'HIL','fullName':'Hardware in loop','description':'硬件在环测试'},
{'simpleName':'HLW','fullName':'Hazardous Location Warning','description':'道路危险状况预警'},
{'simpleName':'HMI','fullName':'Human Machine Interface','description':'人机交互界面'},
{'simpleName':'HSM','fullName':'Hardware Security Module','description':'硬件安全模块'},
{'simpleName':'HTTPS','fullName':'Hyper Text Transfer Protocol over Secure Layer','description':'安全套接字层超本文传输协议'},
{'simpleName':'HV','fullName':'Host Vehicle','description':'主车'},
{'simpleName':'IA','fullName':'Information Age','description':'消息生存周期'},
{'simpleName':'ICW','fullName':'Intersection Collision Warning','description':'交叉路口碰撞预警'},
{'simpleName':'ID','fullName':'Identification','description':'标识'},
{'simpleName':'IP','fullName':'Internet Protocol','description':'网际互连协议'},
{'simpleName':'IPG','fullName':'Inter-Packet Gap','description':'收包间隔'},
{'simpleName':'IPV4','fullName':'Internet Protocol Version 4','description':'互联网协议的第四版'},
{'simpleName':'IPV6','fullName':'Internet Protocol Version 6','description':'互联网协议的第六版'},
{'simpleName':'ISO','fullName':'International Standards Organization','description':'国际标准化组织'},
{'simpleName':'ITS','fullName':'Intelligent Transportation Systems','description':'智能交通系统'},
{'simpleName':'ITT','fullName':'Inter-Transmit Time','description':'发包间隔'},
{'simpleName':'IVS','fullName':'In-Vehicle Signage','description':'车内标牌'},
{'simpleName':'LCW','fullName':'Lane Change Warning','description':'变道预警'},
{'simpleName':'LDW','fullName':'Lane Departure Warning','description':'车道偏离预警'},
{'simpleName':'LED','fullName':'Light Emitting Diode','description':'发光二极管'},
{'simpleName':'LTA','fullName':'Left Turn Assistant','description':'左转辅助'},
{'simpleName':'LTE','fullName':'Long Term Evolution','description':'长期演进技术'},
{'simpleName':'LTE-V2X','fullName':'LTE Vehicle to Everything','description':'基于LTE的车联网无线通信技术'},
{'simpleName':'MAP','fullName':'MAP','description':'地图消息'},
{'simpleName':'MEC','fullName':'Moblie Edge Computing','description':'边缘计算技术'},
{'simpleName':'MIB','fullName':'Management Information Base','description':'管理信息库'},
{'simpleName':'MIL','fullName':'Model In Loop','description':'模型在环测试'},
{'simpleName':'MTBF','fullName':'Mean Time Between Failure','description':'平均故障间隔时间'},
{'simpleName':'Nano SIM','fullName':'Nano SIM卡','description':'新一代的手机SIM卡'},
{'simpleName':'NHTSA','fullName':'National Highway Traffic Safety Administration','description':'美国高速公路安全管理局'},
{'simpleName':'NSA','fullName':'Non－Standalone','description':'非独立组网'},
{'simpleName':'NTP','fullName':'Network Time Protocol','description':'网络时间协议'},
{'simpleName':'NV','fullName':'Normal Vehicle','description':'未装载通信系统的普通车辆'},
{'simpleName':'OBU','fullName':'On-Board Unit','description':'车载单元'},
{'simpleName':'OMC','fullName':'Operation and Maintenance Center','description':'操作维护中心'},
{'simpleName':'OTG','fullName':'OTG','description':'主要应用于不同的设备或移动设备间的联接，进行数据交换'},
{'simpleName':'P2P','fullName':'Point to Point','description':'点对点'},
{'simpleName':'PAM','fullName':'Parking Area Map','description':'停车场地图'},
{'simpleName':'PAM','fullName':'Parking Area Message','description':'停车场地图'},
{'simpleName':'PC5','fullName':'PC5','description':'使用V2X业务UE之间用户面进行D2D直接通信的接口'},
{'simpleName':'PDC','fullName':'Probe Data Collection','description':'浮动车数据采集'},
{'simpleName':'PER','fullName':'Packet Error Ratio','description':'丢包率'},
{'simpleName':'PIL','fullName':'Processor In Loop','description':'处理器在环测试'},
{'simpleName':'PoE','fullName':'Power Over Ethernet','description':'有源以太网'},
{'simpleName':'PSE','fullName':'Power Sourcing Equipment','description':'供电设备'},
{'simpleName':'PSM','fullName':'Personal Safety Message','description':'个体安全消息'},
{'simpleName':'QoS','fullName':'Quality of Service','description':'服务质量'},
{'simpleName':'RJ45','fullName':'Registered Jack45','description':'标准8位模块化接口'},
{'simpleName':'RLVW','fullName':'Red Light Violation Warning','description':'闯红灯预警'},
{'simpleName':'RS232','fullName':'RS232','description':'异步传输标准接口'},
{'simpleName':'RSA','fullName':'Road Side Alert','description':'路侧单元发布的交通事件消息'},
{'simpleName':'RSC','fullName':'Road Side Coordination','description':'路侧协调消息'},
{'simpleName':'RSI','fullName':'Road Side Information','description':'路侧信息'},
{'simpleName':'RSM','fullName':'Road Side Message','description':'路侧单元消息'},
{'simpleName':'RSSI','fullName':'Received Signal Strength Indication','description':'接收的信号强度指示'},
{'simpleName':'RSU','fullName':'Road Side Unit','description':'路侧单元'},
{'simpleName':'RTCM','fullName':'Radio Technical Commission for Maritime Services','description':'国际海运事业无线电技术委员会'},
{'simpleName':'RTK','fullName':'Real-Time Kinematic','description':'实时动态'},
{'simpleName':'RTS','fullName':'Road Tolling Service','description':'道路收费服务'},
{'simpleName':'RV','fullName':'Remote Vehicle','description':'远车'},
{'simpleName':'SA','fullName':'Standalone','description':'独立组网'},
{'simpleName':'SAE','fullName':'Society of Automotive Engineers','description':'美国汽车工程师学会'},
{'simpleName':'SDK','fullName':'Software Development Kit','description':'软件开发工具包'},
{'simpleName':'SDS','fullName':'Sensor Data Sharing','description':'感知数据共享'},
{'simpleName':'SIL','fullName':'Software In Loop','description':'软件在环测试'},
{'simpleName':'SLW','fullName':'Speed Limit Warning','description':'限速预警'},
{'simpleName':'SNMP','fullName':'Simple Network Management Protocol','description':'简单网络管理协议'},
{'simpleName':'SON','fullName':'Self-Organizing Network','description':'自组织网络'},
{'simpleName':'SPAT','fullName':'Signal Phase and Timing Message','description':'信号灯相位与配时消息'},
{'simpleName':'SPI','fullName':'Service Provider Interface','description':'服务提供者接口'},
{'simpleName':'SSM','fullName':'Sensor Sharing Message','description':'感知共享消息'},
{'simpleName':'SVW','fullName':'Signal Violation Warning','description':'闯红灯预警'},
{'simpleName':'TC','fullName':'Target Classification','description':'目标分类'},
{'simpleName':'TCP','fullName':'Transmission Control Protocol','description':'传输控制协议'},
{'simpleName':'TCS','fullName':'Traction Control System','description':'牵引力控制系统'},
{'simpleName':'TDDLTE','fullName':'Time Division Duplexing LTE','description':'时分双工LTE'},
{'simpleName':'TE','fullName':'Tracking Error','description':'位置跟踪误差'},
{'simpleName':'TEST','fullName':'TEST','description':'提供测试使用的私有消息格式'},
{'simpleName':'TJW','fullName':'Traffic Jam Warning','description':'前方拥堵提醒'},
{'simpleName':'TLS','fullName':'Transport Layer Security','description':'安全传输层协议'},
{'simpleName':'TPM','fullName':'Traffic Probe Message','description':'交通信息浮动采集消息'},
{'simpleName':'TTC','fullName':'Time-to-Collision','description':'碰撞预计时间'},
{'simpleName':'TTI','fullName':'Time-to-Intersection','description':'到达交叉口预计时间'},
{'simpleName':'UDP','fullName':'User Data Protocol','description':'用户数据报协议'},
{'simpleName':'UPER','fullName':'Unaligned Packet Encoding Rules','description':'非对齐压缩编码规则'},
{'simpleName':'UTC','fullName':'Coordinated Universal Time','description':'协调世界时'},
{'simpleName':'Uu','fullName':'User to Network interface Universal','description':'Uu空中接口实现UE和EUTRAN的通信'},
{'simpleName':'V2I','fullName':'Vehicle to Infrastructure','description':'车载单元与路侧单元通信'},
{'simpleName':'V2P','fullName':'Vehicle to Pedestrians','description':'车载单元与行人设备通信'},
{'simpleName':'V2V','fullName':'Vehicle to Vehicle','description':'车载单元之间通信'},
{'simpleName':'V2X','fullName':'Vehicle to Everything','description':'车载单元与其他设备通信'},
{'simpleName':'VIN','fullName':'Vehicle ID Number','description':'车辆识别码'},
{'simpleName':'VIR','fullName':'Vehicle Intention And Request','description':'车辆意图和请求'},
{'simpleName':'VNFP','fullName':'Vehicle Near-Field Payment','description':'汽车近场支付'},
{'simpleName':'VPM','fullName':'Vehicle Payment Message','description':'车辆支付消息'},
{'simpleName':'VRU','fullName':'Vulnerable Road User','description':'弱势交通参与者'},
{'simpleName':'VRUCW','fullName':'Vulnerable Road User Collision Warning','description':'弱势交通参与者碰撞预警'},
{'simpleName':'VRUSP','fullName':'Vulnerable Road User Safe Passing','description':'弱势交通参与者安全通行'},
{'simpleName':'WEB','fullName':'World Wide Web','description':'全球广域网'},
{'simpleName':'LKA','fullName':'Lane Keeping Assist','description':'车道保持辅助'},
{'simpleName':'ACC','fullName':'Adaptive Cruise Control','description':'自适应巡航控制'},
{'simpleName':'MQTT','fullName':'Message Queuing Telemetry Transport','description':'消息队列遥测传输协议'},
{'simpleName':'AEB','fullName':'Autonomous Emergency Braking','description':'自动紧急制动'},
{'simpleName':'ESP','fullName':'Electronic Stability Program','description':'车身电子稳定系统'},
{'simpleName':'0S','fullName':'A abbreviation which equals to PPAP','description':'零批量，类似于生产件批准程序'},
{'simpleName':'3/6/12MIS','fullName':'3/6/12 Month in Service Incidents per Thousand Vehicle','description':'使用3/6/12月的每千辆车故障数'},
{'simpleName':'2TP','fullName':'A abbreviation which means that supplier launches  pre-production to verify the production capability. GM names it as  GP9.','description':'两日生产，指供应商进行预生产来验证其批产能力。通用称为GP9'},
{'simpleName':'3C/CCC','fullName':'China Compulsory Certification','description':'中国强制认证'},
{'simpleName':'3G','fullName':'Go and See, Get the Fact, Grasp the Countermeasure','description':'开展现场调查，了解问题根本原因，制定出有效措施'},
{'simpleName':'3M','fullName':'Muda, Mura, Mari','description':'浪费，无稳，无理（日文）——常作改善的核查点'},
{'simpleName':'3P','fullName':'Position, Person, Performance','description':'岗位，能力，绩效（付薪制度）'},
{'simpleName':'4M1E','fullName':'Man, Machine, Material, Method, Environment','description':'人机料法环——现场管理五大要素，问题分析五大方面'},
{'simpleName':'5M','fullName':'Man, Machine, Material, Method, Measure','description':'人员，机器，材料，方法，测量'},
{'simpleName':'5M1E','fullName':'Man, Machine, Material, Method, Measure, Environment','description':'人机料法环测'},
{'simpleName':'5S','fullName':'1. Seiri, Seiton, Seiso, Seiketsu, Shitsuke','description':'整理，整顿，清扫，清洁，修养（日语）'},
{'simpleName':'5W2H','fullName':'Who, What, When, Where, Why, How, How many','description':'何人，何事，何时，何地，为何，如何，多少'},
{'simpleName':'6  Sigma','fullName':'6 Sigma - Continuous improvement method that is designed to  improve products and services by improving the processes  by which they are','description':'六西格玛——是持续改进方法之一，通过改进产品生产工艺而改进产品及服务。'},
{'simpleName':'8D','fullName':'8 Discipline, Method that approach to identify and eliminate  the root cause of a problem.','description':'问题解决的8个步骤法，明确并消除问题的根本原因的方法。'},
{'simpleName':'AAR','fullName':'1. Appearance Approval Report','description':'外观批准报告/外观手册'},
{'simpleName':'ADSL','fullName':'Asymmetric Digital Subscriber Line - a technology for  transmitting digital information at a high bandwidth on existing phone lines  to homes and businesses,providing continously-available, "always  on" connection,ADSL is asymmetric in that it uses most of the channel to  transmit downstream to the user and only a small part to receive  information from the user.','description':'非对称数字用户线——在现有的电话线上以高带宽传输数字信息的一项技术，提供永远在线的连接方式。因其使用大部分信道传输下行的到达用户端的信息，只一小部分传输上行数据，所以是非对称的。'},
{'simpleName':'AFS','fullName':'American Foundry Standards','description':'美国铸造标准'},
{'simpleName':'AG','fullName':'Automotive Group','description':'汽车集团'},
{'simpleName':'AGV','fullName':'Automatic Guided Vehicle','description':'自动导向车辆'},
{'simpleName':'AIAG','fullName':'Automotive Industry Action Group - AIAG is a famous global  organization which is founded by Daimler-Chrysler AG,Ford Motor Co.,General  Motors Corp..','description':'汽车工业行动集团——AIAG 成立于1982年，是戴姆勒-克莱斯勒 (DaimlerChrysler AG)、福特汽车  (Ford Motor Co.)、通用汽车 (General Motors Corp.) 三大汽车公司共同创建的全球公认的著名的组织。'},
{'simpleName':'AISI','fullName':'American Iron and Steel Institue','description':'美国钢铁协会'},
{'simpleName':'AME','fullName':'Advanced Manufacturing Engineer','description':'前期制造工程师'},
{'simpleName':'Andon','fullName':'A Kind of Visual Control System','description':'暗灯系统（一种可视化的讯号系统）'},
{'simpleName':'ANOM','fullName':'Analysis of Means','description':'中位数分析'},
{'simpleName':'ANOVA','fullName':'Analysis of Variance','description':'方差分析'},
{'simpleName':'ANSI','fullName':'American National Standards Institute','description':'美国国家标准协会'},
{'simpleName':'AOP','fullName':'Annual Operating Plan','description':'年度运作计划'},
{'simpleName':'AOQ','fullName':'Average Outgoing Quality','description':'平均出货质量'},
{'simpleName':'AOQL','fullName':'Average Outgoing Quality Limit','description':'平均出货质量界限'},
{'simpleName':'APS','fullName':'Advanced Planning and Scheduling','description':'前期计划和排程'},
{'simpleName':'APW','fullName':'Average Production Weekly','description':'周平均产能'},
{'simpleName':'AQE','fullName':'Advanced Quality Engineer','description':'前期质量工程师'},
{'simpleName':'AQL','fullName':'Acceptable Quality Level','description':'接收准则'},
{'simpleName':'AQP','fullName':'Advanced Quality Planning','description':'前期质量策划'},
{'simpleName':'APQP','fullName':'Advanced Product Quality Planning ','description':'产品质量先期策划'},
{'simpleName':'ARR','fullName':'Architectural Requirements Review','description':'外观需求评审'},
{'simpleName':'ASA','fullName':'American Standards Association','description':'美国标准协会'},
{'simpleName':'ASG','fullName':'Automotive Systems Group - Automotive Systems Group which  belong to','description':'汽车系统集团——江森自控公司 (JCI)下属的汽车系统集团 (ASG).'},
{'simpleName':'ASL','fullName':'Approved Supplier List - A list of approved suppliers qualified to supply certain types of commodities.','description':'合格供方清单——一份列出所有被验证的有资格提供某种类型产品的供应商的清单。'},
{'simpleName':'ASN','fullName':'Advanced Shipping Notice, A network operation system which helps suppliers inform customers those shipping related information such as quantity, control number before shipping.','description':'事先的发料单，指供应商应具有的一种交货提前通知的电脑连网操作系统。从而使其在出货之前，将出货资料诸如数量、货号等信息传递给客户。'},
{'simpleName':'ASP','fullName':'Application Services Provider - It is a company that offers    individuals or enterprises access over the Internet to applications and  related services that would otherwise have to be located in their own  personal or enterprise','description':'应用服务提供商——一种为个人或企业级用户提供通过Internet访问应用程序或相关服务的公司。从而，上述应用程序或相关服务就不必存在于用户自己的个人电脑或企业服务器上。'},
{'simpleName':'ASQE','fullName':'Advanced Supplier Quality Engineer','description':'前期供应商质量工程师'},
{'simpleName':'ASSY','fullName':'Assembly','description':'总成'},
{'simpleName':'ASTM','fullName':'American Society for Testing and Materials','description':'美国材料实验协会'},
{'simpleName':'ATA','fullName':'Anti-trap Algorithm','description':'防夹力算法'},
{'simpleName':'ATI','fullName':'ATI Industrial Automation','description':'公司名称，ATI工业自动化，主要业务为机器人末端执行器和自动化工'},
{'simpleName':'ATM','fullName':'Asynchronous Transfer Mode - It is a dedicated-connection  switching technology that organizes digital data into 53-byte cell units and  transmits them over a physical medium using digital signal technology.  Individually, a cell is processed asynchronously relative to other related  cells and is queued before being multiplexed over the transmission  path.','description':'异步传输模式——一种专用交换技术，它把数据分割成53字节的信  元，用数字信号通过物理介质传输。每个信元独立异步传输，且在通过复用技术传输前被排队。'},
{'simpleName':'ATS','fullName':'Anti Trap System','description':'汽车天窗的安全防夹系统'},
{'simpleName':'ATT','fullName':'1. Anti Trap Test','description':'汽车天窗的安全防夹功能的测试'},
{'simpleName':'AV','fullName':'Appraiser Variation','description':'评价者变差'},
{'simpleName':'AW','fullName':'Arc welding','description':'弧焊'},
{'simpleName':'B2B','fullName':'Business to Business - It is the exchange of products, services,  or information between businesses.','description':'电子商务交流平台——是指互联网上企业间产品、服务、信息的交换'},
{'simpleName':'B2C','fullName':'Business to Customer - B2C is the retailing part of e-commerce  on the Internet.','description':'企业对消费者的商务—— 是指互联网上开展的电子商务中网上零售业务部分。'},
{'simpleName':'BB','fullName':'Black Belt - Six sigma project coordinator','description':'黑带——6σ项目协调人'},
{'simpleName':'BBP','fullName':'Best Busniess Practice','description':'最佳业务实践'},
{'simpleName':'BBS','fullName':'Bulletin Board System','description':'电子公告牌系统'},
{'simpleName':'BCM','fullName':'Body Control Module','description':'车身控制模块'},
{'simpleName':'BET','fullName':'Business Engagement Team','description':'业务报价团队'},
{'simpleName':'BI','fullName':'Business Intelligence','description':'商务智能'},
{'simpleName':'BIOS','fullName':'Basic Input Output System','description':'基本输入输出系统'},
{'simpleName':'BIW','fullName':'Body in White','description':'白车身'},
{'simpleName':'BLTS','fullName':'Bottom Load Top Slider','description':'汽车天窗的一种配置形式，滑轨在上部，天窗在车内滑动'},
{'simpleName':'BMG','fullName':'Bau Muster Genehmigung','description':'产品工程样件性能检验认可(德文）——大众汽车集团通用缩略语。'},
{'simpleName':'BOL','fullName':'Bill of Labor','description':'工时清单'},
{'simpleName':'BOM','fullName':'Bill of Material - Diagram or record of all the components of  an item, the parent-component relationships and usage  quantities.','description':'物料清单——所有零件，其上级零件关系和使用量的记录和图表。'},
{'simpleName':'BOS','fullName':'Business Operating System - The integrative management system  of JCI, US.','description':'业务运作系统——美国江森自控汽车系统集团综合管理体系。'},
{'simpleName':'BOT','fullName':'Bill of Tooling','description':'工装清单'},
{'simpleName':'BPR','fullName':'Business Process Reengineering','description':'业务流程再设计'},
{'simpleName':'BR','fullName':'Burning Rate','description':'燃烧速度'},
{'simpleName':'BSC','fullName':'Balanced Score Card','description':'平衡计分卡'},
{'simpleName':'BSI','fullName':'British Standards Institute','description':'英国标准协会'},
{'simpleName':'BSR','fullName':'Buzz, Squeak,and Rattle','description':'嗡嗡，吱吱，格格的噪声'},
{'simpleName':'BTP','fullName':'Build to Print','description':'按图施工的项目'},
{'simpleName':'BU','fullName':'Business Unit','description':'业务单元'},
{'simpleName':'BUIT','fullName':'Business Unit Information Technology','description':'业务单元信息技术'},
{'simpleName':'C2C','fullName':'Customer to Customer - Consumer self providing services or  product is it is individual worker providing services to be given to by the  form that the consumer, frequently sees other most other  consumer','description':'消费者对消费者的商务——消费者本身提供服务或产品给其他消费者, 最常见的形态就是个人工作者提供服务给其他消费者'},
{'simpleName':'CA&PA','fullName':'Correction Action and Prevention Action','description':'纠正和预防措施'},
{'simpleName':'CAB','fullName':'Curtain Airbag','description':'气帘式安全气囊'},
{'simpleName':'CAD','fullName':'Computer Aided Design','description':'计算机辅助设计'},
{'simpleName':'CAE','fullName':'Computer Aided Engineering','description':'计算机辅助工程'},
{'simpleName':'CAM','fullName':'Computer Aided Manufacturing','description':'计算机辅助制造'},
{'simpleName':'CAPEX','fullName':'Capital Expenditures','description':'资本性支出'},
{'simpleName':'CAR','fullName':'Capital Appropriation Request - Form established to approve  spending money for capital assets.','description':'资本拨款申请——用于批准资本性支出的表格。'},
{'simpleName':'CARE','fullName':'Customer, Acceptance, Review,  Evaluation','description':'验证岗位（顾客，接受，评审，评估）'},
{'simpleName':'CASE','fullName':'Computer-aided Software Engineering - It is the use of a computer-assisted method to organize and control the development of software,  especially on large, complex projects involving many software components and  people. Using CASE allows designers, code writers, testers, planners, and  managers to share a common view of where a project stands at each stage of','description':'计算机辅助软件工程——使用计算机工具来帮助管理软件——特别是大的，复杂的，涉及很多组件和人员的项目——的开发。使用CASE可以让设计人员，开发人员，测试人员，计划人员及管理人员对项目进展的每一阶段都有一个统一的认识。'},
{'simpleName':'CAT  5','fullName':'Category 5 cable used for computer connectivity','description':'5类用于电脑连接的网线'},
{'simpleName':'CAT  6','fullName':'Category 6 cable used for computer connectivity','description':'6类用于电脑连接的网线'},
{'simpleName':'CATIA','fullName':'Computer-Graphics Aided Three-Dimensional Interactive  Application - Full wire frame, surface and solid modeling tool for  computer-aided design.','description':'3-D制图软件——用计算机设计线框、曲面、实体模型的工具。'},
{'simpleName':'CATV','fullName':'Cable Television (Coaxial wire for sending video signals to  displays)','description':'发送显示的视频信号的同轴线'},
{'simpleName':'CBU','fullName':'Customer Business Unit - A kind of  software which can help the customer to develop customer financial  strategies, evaluate business cases, review and approve customer quotes as well as to  Responsible for growth of assigned','description':'客户业务单元——一种可以用来帮助客户发展其经济平台，估算其商 务能力，报价以及对业务发展'},
{'simpleName':'CC','fullName':'1. Critical Characteristics - CC are those product requirements  (Dimensions, Specifications Tests) or process parameters which can affect  compliance with government regulations or safe Vehicle/Product Function and  which require specific producer, assembly, shipping or monitoring actions and  inclusion on the Control Plan.','description':' 关键特性——指那些能影响政府法规符合性或车辆/产品功能安全性，且应包括在控制计划之中需要特殊生产者，装配，发运，或监控措施的产品要求(尺寸，规范，试验)或过程参数。'},
{'simpleName':'CCP','fullName':'Critical Control Point','description':'关键控制点'},
{'simpleName':'CCW','fullName':'Counter Clock Wise','description':'逆时针方向的'},
{'simpleName':'CD-ROM','fullName':'Compact Disk,Read Only Memory - A mass data memory system  of CD(Compact Disc) format to change CD(Compact  Disc) to DA(Digital','description':'只读光盘——将CD转换成数字音频的CD格式大容量数据记忆系统。'},
{'simpleName':'CD-RW','fullName':'Compact Disk,Rewriteable - A rewriteable mass data memory  system of CD(Compact Disc) format to change CD(Compact  Disc) to DA(Digital','description':'可擦写光盘——将CD转换成数字音频的CD格式大容量可擦写数据记忆'},
{'simpleName':'CE&T','fullName':'Capital Equipment and Tooling','description':'固定资产和设备'},
{'simpleName':'CF','fullName':'Cash Flow','description':'现金流'},
{'simpleName':'CFT','fullName':'Cross Functional Team','description':'横向职能小组'},
{'simpleName':'CGI','fullName':'Common Gateway Interface','description':'公用网关接口'},
{'simpleName':'CHESS','fullName':'Corporate Health, Environmental and Safety System','description':'安全、环境和员工健康提醒'},
{'simpleName':'Christmas  Tree','fullName':'Christmas Tree - Undirectional plastic pin that attaches  material to the frame with relative ease.','description':'圣诞树——无固定方向的塑料销，用于方便地连接其他材料和骨架。'},
{'simpleName':'CID','fullName':'Continuous Improvement Discusstion - Be used for performance  appraisal of salary staff, the appraisal grade is U(Unacceptable), LP(Less  Than Full Performance), FP(Full Performance), E(Excellent), D(Distinguished).','description':'持续改进讨论——用于薪水工业绩评估,评估等级分为完全不合格/低 于合格/完全合格/优秀/杰出。'},
{'simpleName':'CIM','fullName':'Computer Integrated Manufacturing','description':'计算机集成制造'},
{'simpleName':'CIP','fullName':'Continuous Improvement Plan - CIP is prepared concurrently with  the Operational Plan and documents the actions to be taken in response to  the identified opportunities for people, process and  product improvement.','description':'持续改进计划——持续改进计划是与运营计划同时制定的，并把识别出的对人员、工艺及产品改进机会所采取的措施文件化。'},
{'simpleName':'CKD','fullName':'Completely Knocked Down','description':'完全拆缷——是以全散件形式作为进口整车车型的一种专有名词术  语，全散件可以是进口零部件，也可以是本地生产的零部件。在当地生产的零部件以较低的关税和较低的工资，利用当地劳动力组装成整'},
{'simpleName':'Cmk','fullName':'Machine Capability index','description':'设备能力指数'},
{'simpleName':'CMM','fullName':'Coordinate Measurement Machine - An instrument used to measure  three dimensional size.','description':'三坐标测量仪——俗称三坐标，用于测量三维尺寸的仪器。'},
{'simpleName':'CMT','fullName':'China Management Team','description':'中国管理团队'},
{'simpleName':'CNC','fullName':'Computerized Numerically Controlled','description':'数控成型生产小型或中型的批量较为复杂的样件'},
{'simpleName':'C-NCAP','fullName':'China - New Car Assessment Program','description':'中国新车评估测试'},
{'simpleName':'COE','fullName':'Center of Excellence','description':'卓越中心'},
{'simpleName':'Contribution  Margin','fullName':'Contribution Margin - It amounts to net sales minus variable  cost. The variable cost, namely the cost in proportion to  production or sales such as materials in concepts of western management  accounting.','description':'边际贡献 - 公式＝销售净收入(已减去折扣与折让)－变动成本'},
{'simpleName':'COP','fullName':'1. Customer Oriented Process','description':'顾客导向过程'},
{'simpleName':'COQ','fullName':'Cost of Quality','description':'质量成本'},
{'simpleName':'Cp','fullName':'Capability Index of Process','description':'稳定过程的能力指数，定义为容差宽度除以过程能力，不考虑过程有'},
{'simpleName':'CP','fullName':'Control Plan','description':'控制计划'},
{'simpleName':'CPI','fullName':'1. Combined Probability of Injury','description':'头胸伤害组合概率（用于NCAP评价）'},
{'simpleName':'CPIP','fullName':'Current Product Improvement Process','description':'产品改进过程'},
{'simpleName':'Cpk','fullName':'Complex Process Capability index - The capability index for a  stable','description':'过程能力指数——稳定过程的能力指数。'},
{'simpleName':'CPL','fullName':'Complex Process Lower Index','description':'稳定过程的下限能力指数，定义为容差范围下限除以实际过程分布宽'},
{'simpleName':'CPM','fullName':'Corporate Performance Management','description':'公司绩效管理'},
{'simpleName':'CPPM','fullName':'Customer Parts Per Million','description':'顾客（产品更换）百万分率'},
{'simpleName':'CPU','fullName':'Complex Process Upper Index','description':'稳定过程的上限能力指数，定义为容差范围上限除以实际过程分布宽度上限'},
{'simpleName':'CPV','fullName':'Cost Per Vehicle','description':'每辆车索赔费用'},
{'simpleName':'CRM','fullName':'Customer Relationship Management','description':'客户关系管理'},
{'simpleName':'CRP','fullName':'1. Capacity Requirement Plan','description':'能力需求计划'},
{'simpleName':'CRS','fullName':'Child Restraint System','description':'儿童保护系统'},
{'simpleName':'CS1','fullName':'Controlled Shipping 1','description':'一级受控发运'},
{'simpleName':'CS2','fullName':'Controlled Shipping 2','description':'二级受控发运'},
{'simpleName':'CSO','fullName':'Craftsmanship Sign-Off','description':'精致工艺签发'},
{'simpleName':'CT','fullName':'Cycle Time','description':'周期时间'},
{'simpleName':'CTD','fullName':'Cumulative Trauma Disorder - Referring to is incorrect use the  computer display or uses discomfort brought about by computer excessively, happen generally in need all the year round finesse organizes with chronic  inflammation swelling , the main nerve wound appearing on meeting under grave  condition from finesse to the arm becomes fragile , brings along pain','description':'重复性积累伤害——指的是不正确使用电脑显示器或者过分使用电脑所造成的身体不适，通常发生在需要长年累月使用电脑的职业中，手腕组织将慢性的发炎肿胀，严重的情况下还会出现伤口从手腕到手臂的主要神经变得脆弱，带来疼痛和手指僵硬。'},
{'simpleName':'CVIS','fullName':'Complete Vehicle Inspection Standard','description':'整车检验标准'},
{'simpleName':'CW','fullName':'Clock Wise','description':'顺时针方向的'},
{'simpleName':'DA','fullName':'Deviation Authorization','description':'临时更改授权书——在未发放正式的ECR报告前，提供临时性更改的依据文件。'},
{'simpleName':'DCP','fullName':'Dynamic Control Plan','description':'动态控制计划(尺寸控制计划)'},
{'simpleName':'DDP','fullName':'Delivery Duty Paid','description':'进口税已付，目的地交货'},
{'simpleName':'DF','fullName':'Degree of Freedom','description':'自由度'},
{'simpleName':'DFA','fullName':'Design for Assembly','description':'装配性设计'},
{'simpleName':'DFM','fullName':'Design for Manufacturing - Product delivery process with the  objective of attaining a product that may be easily  manufactured at a low cost.','description':'制造性设计——从低成本、易于制造的角度进行产品设计。'},
{'simpleName':'DFMA','fullName':'Design for Manufacture and Assembly','description':'制造和装配设计'},
{'simpleName':'DFMEA','fullName':'Design Failure Mode and Effects Analysis - Is a document used  to identify potential failure modes for the product.','description':'设计的潜在失效模式分析——用于确认产品潜在失效模式的文件。'},
{'simpleName':'DHCP','fullName':'Dynamic Host Config Protocol - it is a communications protocol  that lets network administrators manage centrally and automate the assignment  of IP addresses in an organizations network.','description':'动态主机配置协议——使网络管理员能够集中管理和自动分配网络IP地址的通信协议。'},
{'simpleName':'DIN','fullName':'Deutsches Institut fǖr Normung - Germany industry standard','description':'德国标准化委员会(德文）——德国工业标准'},
{'simpleName':'DIY','fullName':'Do It Yourself - Do It Yourself (DIY) refers to the practice of  fabricating or repairing things.','description':'自己动手——自己动手包括自己动手制造和修理东西。'},
{'simpleName':'DLL','fullName':'Dynamic Link Liberary - it is a  grams,  any of which can be called when needed by a larger program that is running in  the computer. The small program that lets the larger program communicate with  a specific device such as a printer or scanner is often packaged as a  DLL program (usually referred to as a DLL file).','description':'动态链接库 -  一种随时可被大软件调用的程序包,使大程序可同打印机，扫描仪之类设备通信,通常被打包成DLL程序（通常称为DLL文件）'},
{'simpleName':'DMAIC','fullName':'Define/Measure/Analyze/Improve/Control - Technique where key  product- process performance variables are measured, analyzed, improved,  and  controlled using statistical methods.','description':'定义/衡量/分析/改进/控制——使用统计方法对关键产品工艺性能变量进行衡量，分析，改进，并控制的技术。'},
{'simpleName':'DMR','fullName':'Discrepant Material Report','description':'差异材料报告'},
{'simpleName':'DNS','fullName':'1. Domain Network Server','description':'1. 区域网络服务器'},
{'simpleName':'DOE','fullName':'Design of Experiments','description':'试验设计——用应用统计方法进行策划、开展、分析和解释受控测试来评估控制变量值或变量组的因素。'},
{'simpleName':'DOH','fullName':'Days on Hand','description':'存货周转周期'},
{'simpleName':'DOS','fullName':'Days Of Store','description':'存货天数和库存天数'},
{'simpleName':'DOS','fullName':'Disk Operation System - An operating system that resides on a  disk.','description':'磁盘操作系统——磁盘操作系统是早期个人电脑上使用的一种主要操作系统，它是一个单用户单任务的操作系统。这是一个基于磁盘管理的操作系统。与我们现在使用的操作系统最大的区别在于，它是命令行形式的，靠输入命令来进行人机对话，并通过命令的形式把指令传给计算机，让计算机实现操作的。所以操作方式也非常简单，只需输'},
{'simpleName':'DPCA','fullName':'Dongfeng Peugeot Citroen Automobile Co. Ltd','description':'神龙汽车有限公司'},
{'simpleName':'DRE','fullName':'Design Release Engineer','description':'设计发布工程师'},
{'simpleName':'DRL','fullName':'Direct Run Loss','description':'一次生产通过率损失'},
{'simpleName':'DSO','fullName':'Design Sign-Off','description':'设计签发'},
{'simpleName':'DTC','fullName':'Diagnostic Trouble Code','description':'故障诊断代码'},
{'simpleName':'DTS','fullName':'Dimensional Technical Specifications','description':'外观技术规格'},
{'simpleName':'DUNS','fullName':'Data Universal Numbering System','description':'邓氏编码'},
{'simpleName':'DV','fullName':'Design Validation','description':'设计验证'},
{'simpleName':'DVP','fullName':'Design Verification Plan - Document describing a plan for  verifying that a product (in prototype form) will meet product  specifications.','description':'设计验证计划——确认产品符合产品技术规格的计划。'},
{'simpleName':'DVP&R','fullName':'Design Verification Plan and Report','description':'设计验证计划和报告'},
{'simpleName':'EAM','fullName':'Enterprise Assets Management','description':'企业资产管理'},
{'simpleName':'EBIT','fullName':'Earnings Before Interest and Tax - Company profit excluding  interest and income tax.','description':'息税前利润——指企业所有者通过经营活动后,获得销售利润;不包括利息和缴纳所得税的盈利。'},
{'simpleName':'EBOM','fullName':'Engineering Bill of Material','description':'工程物料清单'},
{'simpleName':'ECE','fullName':'Economic Community of Europe - The Economic Commission for  Europe  (ECE) was established in 1947 to encourage  economic cooperation among its','description':'欧共体——欧洲经济委员会成立于1947年，目的是鼓励其成员间的经济合作'},
{'simpleName':'ECM','fullName':'Engineering Change Management','description':'工程变更管理'},
{'simpleName':'ECO','fullName':'Engineering Change Order - Includes a Change Impact Matrix to guide the implementation planning;indentifies all superseded and superseding  items and documents by type,number and revision level.Provides a high  level implementation plan for one or more approved  ECR.','description':'工程变更指令——包括一个更改影响矩阵来指导实施计划，确定所有被取代和将要被取代的零件，并记录标明类型、数量和版本号。对一个或多个已批准的ECR发放高级别的实施计划。'},
{'simpleName':'ECP','fullName':'Engineering Change Process','description':'工程更改流程'},
{'simpleName':'ECR','fullName':'Engineering Change Request - States the recommended action to  solve problems/initiate improvements/release  documents;defines the need for the','description':'工程变更申请——阐述了用于解决问题/发起改进/发放文件的推荐措施，规定了变更的需要。'},
{'simpleName':'ECU','fullName':'Electronic Control Unit','description':'电子控制单元'},
{'simpleName':'EDI','fullName':'Electronic Data Interchange - It is a standard format for  exchanging business','description':'电子数据交换——一种交换商务数据的标准格式。'},
{'simpleName':'EFD','fullName':'EFD Induction','description':'公司名称，易孚迪'},
{'simpleName':'EHS','fullName':'Extremely Hazardous Substances','description':'非常有害的物质'},
{'simpleName':'ELV','fullName':'End of Life Vehicle','description':'报废车辆'},
{'simpleName':'EMC','fullName':'Electro Magnetic Compatibility','description':'电磁兼容性'},
{'simpleName':'EMPB','fullName':'Erst Muster Pruef Bericht','description':'首批样件检验报告(德文）——大众汽车集团通用缩略语。'},
{'simpleName':'EMS','fullName':'Environment Management System - The part of the overall  management system that includes organizational structure, planning  activities, responsibilities, practices, procedures, processes and resources  for developing, implementing, achieving, receiving  and maintaining the','description':'环境管理系统——整个管理体系的一个组成部分，包括为制定、实施、实现、评审和保持环境方针所需的组织结构、计划活动、职责、惯例、程序、过程和资源。'},
{'simpleName':'EOAT','fullName':'End of Arm Tooling','description':'机械手末端工具'},
{'simpleName':'EOL','fullName':'1. End of Line','description':'1. 流水线末端，线末'},
{'simpleName':'EP','fullName':'Error Proofing - Removal of all potential causes of error  through design, process, or mistake proofing devices.','description':'防错——通过设计、过程或防止出错的装置来避免所有潜在出错的可能性。'},
{'simpleName':'EPCRA','fullName':'Emergency Planning and Community Right-to-know Act','description':'应急计划'},
{'simpleName':'EPDM','fullName':'Ethylene-Propylene-Diene Monomer','description':'三元乙丙橡胶，含双环戊二稀'},
{'simpleName':'EPIC','fullName':'Enterprise Program Information Collaboration','description':'项目信息交流'},
{'simpleName':'EPL','fullName':'Engineering Parts List','description':'工程零件表'},
{'simpleName':'ERP','fullName':'Enterprise Resource Planning - It is an industry term for the  broad set of activities supported by multi-module application software that  helps a manufacturer or other business manage the important parts of its  business, including product planning, parts purchasing, maintaining  inventories, interacting with suppliers, providing customer service, and  tracking orders.','description':'企业资源计划——一个工业术语，是指制造业或其他企业用来管理生产计划、采购、库存、供应商、客户服务以及跟踪订单等重要业务的软件系统，也可包括财务及人力资源等方面。'},
{'simpleName':'ERT','fullName':'Emergency Response Team - The team  which is to deal with the emergency occurred in the company','description':'紧急抢险队——为对公司发生的突发事件作出迅速反应尽量减少损失而成立的队伍。'},
{'simpleName':'ESD','fullName':'Electro-Static Discharge','description':'静电放电'},
{'simpleName':'ESO','fullName':'Engineering Sign Off','description':'工程签署'},
{'simpleName':'EV','fullName':'Equipment Variation','description':'设备变差'},
{'simpleName':'EVA','fullName':'Economic Value Added','description':'经济增加值（企业业绩评估方法）'},
{'simpleName':'EVOP','fullName':'Evolutionary Operation','description':'调优运算'},
{'simpleName':'EWO','fullName':'Engineering Work Order - The work order  that direct TC to do design work.','description':'工程更改——指导TC进行设计工作的工作单。'},
{'simpleName':'FAQ','fullName':'Frequently Asked Question - the questions which are related  with a relational high frequency','description':'经常性问题——被提出的频率比较高的问题'},
{'simpleName':'FAT','fullName':'Files Allocation Table - It is a table that an operating system  maintains on a hard disk that provides a map of the cluster (the basic unit  of logical storage on a hard disk) that a file has been stored in.','description':'文件分配表——操作系统维护在硬盘上的系统表，它提供了文件占用的簇（硬盘上基本的逻辑存储单元）的映象。'},
{'simpleName':'FCA','fullName':'Free Carrier','description':'货交承运人'},
{'simpleName':'FCST','fullName':'Forecast','description':'预测'},
{'simpleName':'FEA','fullName':'Finite Element Analysis - Mathematical method to evaluate and  predict stress and deflection in manufactured components.','description':'有限元分析——评价和预测压力和变形的数学方法'},
{'simpleName':'FG','fullName':'Finished Goods','description':'成品'},
{'simpleName':'FIFO','fullName':'First In First Out - One of the inventory counting principles,  often used in our country, namely the cost of inventory first in first added  in product costs, so the inventory listed in balance sheets are  close to market value.','description':'先进先出——这是存货计价核算的原则之一（中国常用），即采用先入库的存货，先进入生产成本，使资产负债表上的存货项目更接近现行成本。'},
{'simpleName':'FMEA','fullName':'Failure Mode and Effects Analysis - A systematized group of  activities intended to: 1)recognize and evaluate the potential of a  product/process and its effects, 2)identify actions which could eliminate or  reduce the chance of','description':'失效模式及后果分析——一组系统化的活动旨在：1)找出和评估产品/过程的潜在失效及其后果，2)确定能消除或减少潜在失效发生机会的措施，3)把过程文件化。'},
{'simpleName':'FMS','fullName':'Flexible Manufacturing Systems','description':'柔性制造系统'},
{'simpleName':'FOB','fullName':'Free on Board - The total cost of the suppliers who are in charge of carrying the goods from the plant to the ship','description':'离岸价——供应商负责把货物从工厂运到船上的费用，这里包括拖柜费用、报关和租仓（如果存放时间比较久）的费用算在内的价格。'},
{'simpleName':'FPIR','fullName':'First Piece Inspection Report','description':'首件检查报告'},
{'simpleName':'FRW','fullName':'Friction welding','description':'摩擦焊'},
{'simpleName':'FSB','fullName':'Front Seat Back - The backrest of the front seat of a car','description':'前排座椅靠背——汽车前排座椅的靠背'},
{'simpleName':'FSC','fullName':'Front Seat Cushion - The cusion of the front seat of a car','description':'前排座椅座垫——汽车前排座椅的坐垫'},
{'simpleName':'FSO','fullName':'Financial Sign-Off','description':'财务签发'},
{'simpleName':'FTA','fullName':'Fault Tree Analysis','description':'故障树分析'},
{'simpleName':'FTP','fullName':'File Transmission Protocol - It is a standard Internet protocol,  is the simplest way to exchange files between computers.','description':'文件传输协议，标准的互联网协议——标准的互联网协议，是因特网 上两个计算机间交换文件最简单的方式。'},
{'simpleName':'FTQ','fullName':'First Time Quality','description':'一次合格率'},
{'simpleName':'FTT','fullName':'First Time Through','description':'首次合格率'},
{'simpleName':'FW','fullName':'Flash welding','description':'闪光焊'},
{'simpleName':'FY','fullName':'Fiscal Year - The fiscal year of all enterprises is  corresponding to national accounting regulations, according to the rules of  national financial department. The date of our country is from January 1 to  December 31, western country is from April 1(or October 1) to March 31 next  year(or','description':'会计年度——是根据每个国家的财政部规定的财政收支的年度。所有企事业会计核算年度必须与国家规定的会计核算的起迄日期一致。我国会计年度规定是从每年1月1日至12月31日。西方国家有从4月1日起  (也常有是10月1日起)到下一年度3月31日(则到9月30日)至。少数国家是从每年7月1日起至下一年度的6月30日。'},
{'simpleName':'FYI','fullName':'For Your Information','description':'供你参考'},
{'simpleName':'G&A','fullName':'General and Administrative Costs','description':'一般费用与行政费用'},
{'simpleName':'GA','fullName':'General Assembly','description':'通用的装配'},
{'simpleName':'GB','fullName':'Guo Biao','description':'国家标准（中文）'},
{'simpleName':'GCA','fullName':'Global Customer Audit','description':'全球客户评分 （通用汽车全球汽车评分标准）——模拟顾客的眼光，对可售车辆的质量状况进行评定。GCA规范仅适合于全球GM系统所有汽车制造厂，它规定了车辆抽样方案、设施要求、评审项目、评定方'},
{'simpleName':'GD&T','fullName':'Geometric Dimensioning and Tolerancing - Method to minimize production costs by showing the dimension and tolerancing  on a drawing while considering the functions or relationships of part features.','description':'几何尺寸与公差——在考虑零件功能或匹配关系时，通过在图纸上标明尺寸和公差来减少生产成本的方法。'},
{'simpleName':'GDS','fullName':'1. Global Delivery Survey','description':'全球交付审查'},
{'simpleName':'GMAW','fullName':'Gas Metal Arc Welding','description':'熔化极气体保护电弧焊'},
{'simpleName':'GMAW-P','fullName':'Gas Metal Arc Welding - Pulsed','description':'熔化极气体保护脉冲电弧焊'},
{'simpleName':'GMAW-S','fullName':'Gas Metal Arc Welding - Short-circuit Arc','description':'熔化极气体保护短路过度电弧焊'},
{'simpleName':'GMS','fullName':'Global Manufacturing System','description':'全球制造系统'},
{'simpleName':'GP','fullName':'General Procedure','description':'通用程序'},
{'simpleName':'GPC','fullName':'Gage Performance Curve - Used for measuring the repeatability  and variation','description':'量具性能曲线——用于评价量具的重复性和偏值。'},
{'simpleName':'GPDS','fullName':'Global Product Development System','description':'团队评估'},
{'simpleName':'GPS','fullName':'Global Positioning System','description':'全球定位系统'},
{'simpleName':'GQTS','fullName':'Global Quality Tracking System','description':'全球质量跟踪系统'},
{'simpleName':'GR&R','fullName':'Gauge Repeatability & Reproducibility','description':'量具（检具）重复性和再现性'},
{'simpleName':'GSM','fullName':'Global System for Mobil Communication - A digital cellular  phone technology based on TDMA that is the predominant system in Europe, but also used worldwide. Developed in the 1980s, GSM was first deployed in seven  European countries in 1992. It operates in the 900MHz and 1.8GHz  bands in Europe and the 1.9GHz PCS band in the  U.S.','description':'全球移动通讯系统——一种基于时分多址技术的数字蜂窝电话技术，最先在欧洲应用，现在已经在全球范围内广泛应用。从20世纪80年代开始发展，GSM于1992年首先在七个欧洲国家实施应用，在欧洲使用  900MHz和1.8GHz两个波段，在美国使用1.9GHz波段。'},
{'simpleName':'GST','fullName':'Gross Sales Tax','description':'销售总额税'},
{'simpleName':'GVDP','fullName':'Global Vehicle Development Process','description':'整车开发流程'},
{'simpleName':'GVW','fullName':'Gross Vehicle Weight','description':'车辆总重'},
{'simpleName':'HMC','fullName':'Hyundai Manufacturing Company','description':'韩国现代'},
{'simpleName':'HR','fullName':'Human Resources','description':'人力资源'},
{'simpleName':'HSE','fullName':'Health Safety Environment','description':'职业健康和环境与安全体系'},
{'simpleName':'HTKO','fullName':'Hard Tooling Kick-off','description':'硬模启动'},
{'simpleName':'HTML','fullName':'Hyper Text Markup Language - it is the set of markup symbols or  codes inserted in a file intended for display on a  World Wide Web browser page.','description':'超文本标识语言——一组被插入在可用Web浏览器显示的文件中的标识符号或代码的集合'},
{'simpleName':'HVAC','fullName':'Heating, Ventilation and Air Conditioning','description':'加热、通风和空气调节'},
{'simpleName':'I/O','fullName':'Input/Output','description':'输入/输出'},
{'simpleName':'ICT','fullName':'Information Communication Technology','description':'信息、通信和技术，在线测试仪'},
{'simpleName':'IDC','fullName':'International Data Company','description':'国际数据公司'},
{'simpleName':'IDF','fullName':'Intermediate Distribution Frame','description':'电脑网络下部构造的中间配线架'},
{'simpleName':'IDP','fullName':'Individual Development Plan -Be used for career development of  salary','description':'个人发展计划——用于薪水工职业发展。'},
{'simpleName':'IE','fullName':'Industrial Engineering','description':'工业工程'},
{'simpleName':'IGES','fullName':'Initial Graphics Exchange Specification','description':'美国国家标准，它使得图形和基本几何数据可在绘图和造型系统之间'},
{'simpleName':'ILUO','fullName':'Hourly skill assessment standard  - ILUO describes the skill level, I-  undergoing training with constant supervision,L-be able to operate but  requires some  supervision, U-consistently  operates without supervision,O-understanding and complies with standard,φ-be a  trainer','description':'小时工技能评估标准——ILUO描述了员工技能的不同等级和水平，I需培训并经常监督指导，L能操作但需偶尔指导，U无需指导即能进行操作，O理解并遵循标准，φ完全可以作培训员。'},
{'simpleName':'IMDS','fullName':'International Material Data System','description':'国际材料数据系统（汽车行业）'},
{'simpleName':'IMT','fullName':'Inalfa Management Team','description':'英纳法管理团队'},
{'simpleName':'IP','fullName':'Instrument Panel','description':'仪表板'},
{'simpleName':'IPA','fullName':'Iso-propyl Alcohol, Isopropanol','description':'异丙醇'},
{'simpleName':'IPC','fullName':'1. Integrated Production Control (Software for Shop  Floor','description':'综合生产控制（用于工厂的软件）'},
{'simpleName':'IPPM','fullName':'Inner (Internal) Parts per Million','description':'内部（产品缺陷）百万分率'},
{'simpleName':'IPTV','fullName':'Incidents per Thousand Vehicles','description':'每千辆车故障数'},
{'simpleName':'IPV','fullName':'Internal Product Volume','description':'内部生产产量'},
{'simpleName':'IR','fullName':'Incident Report','description':'事故报告'},
{'simpleName':'IRR','fullName':'Internal Rate of Return - The investment decision-making is  based on discount rate by measuring the current value of future cash flow in  and','description':'内部回报率——通过测算需投资项目的未来现金流入的现值的假设下，所求得的贴现率(即项目内含报酬率),再参考银行存款的利息率进行比较，进行投资决策'},
{'simpleName':'IRS','fullName':'Inalfa Roof System','description':'英纳法天窗系统'},
{'simpleName':'ISDN','fullName':'Integrated Services Digital Network - It is a set of standards for digital transmission over ordinary telephone copper wire as well as over  other media.  Integrated Services  Digital Network in concept is the integration of both analog or voice data together with digital  data over the same network.','description':'综合服务数字网络——一组通过普通电话线或其它介质传输数字信号的标准。综合业务数字网从概念上说是把语音或模拟信号同数字信号集成于同一网络。'},
{'simpleName':'ISIR','fullName':'Initial Sample Inspection Report','description':'初始样件检验报告'},
{'simpleName':'ISO','fullName':'International Standards Organization - Including different  kinds of technical standardization for every walk of life. The organization  aims at promoting the standardization and the development of relevant  activities in worldwide, for','description':'国际标准化组织——主要设计各行业各种产品的技术规范，该组织旨在“在世界上促进标准化及其相关活动的发展，以便于商品和服务的国际交换”。'},
{'simpleName':'ISO/TS16949','fullName':'ISO/TS16949 - International automotive quality system  requirements','description':'国际汽车行业质量体系标准'},
{'simpleName':'ISO14001','fullName':'ISO14001 - Environment Management System Standard','description':'环境管理体系标准'},
{'simpleName':'ISO9001','fullName':'ISO9001 - International quality system requirements','description':'国际质量体系标准'},
{'simpleName':'ISP','fullName':'Internet Services Provider - It is a company that provides  individuals and other companies access to the Internet and other  related services such as Web site building and virtual hosting.','description':'互联网服务提供商——一种为个人或企业级用户提供Internet接入或其它相关服务如Web网站架设和虚拟主机服务的公司。'},
{'simpleName':'ISR','fullName':'Initial Sample Report','description':'初始样件报告'},
{'simpleName':'ISW','fullName':'Initial Sample Warrant','description':'初始样件保证书'},
{'simpleName':'IT','fullName':'Information Technology','description':'信息技术'},
{'simpleName':'ITR','fullName':'Inventroy Turnover Rate','description':'库存周转率'},
{'simpleName':'IVER','fullName':'Integration Vehicle Engineering Release','description':'集成车工程发布'},
{'simpleName':'IW','fullName':'Induction welding','description':'感应焊'},
{'simpleName':'J-clip','fullName':'J-clip - Plastic trim fastener in shape of J .','description':'J型条——像J形状的塑料紧固条。'},
{'simpleName':'JCMS','fullName':'Johnson Controls manufacturing system - JCMS originates from  Toyota Lean Manufacturing System which includes 5S/Visual management,  standardized work, problem solving, kaizen, constraint management,  quick changeover, total productive maintenance,  kanban, error proofing, etc.','description':'江森自控制造体系——源自丰田汽车创立的精益生产体系，包括5S和可视化管理、标准化工作、问题解决、改善、制约管理、快速切换、全员生产维护、看板和防错等工具。'},
{'simpleName':'JD','fullName':'Job Description','description':'岗位描述'},
{'simpleName':'JIS','fullName':'Job Instruction Sheets','description':'作业指导书'},
{'simpleName':'JIT','fullName':'Just in Time - A production and inventory method popularized by  the Japanese whereby materials and supplies are delivered to the production  site at the precise time they are needed rather than being stockpiled in  a warehouse at the production site for a future  need.','description':'及时供货——一种由日本人推广普及的生产和库存方式。它的理念是将原材料和供应品准时地按照客户要求发送到生产地点，而不是储存在生产所在地的仓库中以备后用。'},
{'simpleName':'Kaizen','fullName':'Improve - Incremental, measurable continuous improvement.  Technique reflected by on-going, incremental small changes  that have positive impact.','description':'改善（日语）——持续的、可量度的持续改进。通过有正面影响的、不断进行中的、增值的小的改变反映出的技术'},
{'simpleName':'Kanban','fullName':'Authorization to make product-using cards, signals, or similar  mechanisms to communicate process demand upstream.','description':'看板（日语），利用卡片、信号或其它类似的机制来与生产过程的上游联络，从而授权生产。工厂现场管理展示各种信息的展示板的统称'},
{'simpleName':'KCC','fullName':'Key Control Characteristics','description':'关键控制特性'},
{'simpleName':'KCDS','fullName':'Key Characteristic Designation System','description':'关键特性标识系统'},
{'simpleName':'Kick-off  Meeting','fullName':'Kick-off Meeting  - The  first meeting to start a new project.','description':'项目启动会议——一个项目启动时开的第一次会议。'},
{'simpleName':'KM','fullName':'Knowledge Management','description':'知识管理'},
{'simpleName':'KPC','fullName':'Key Product Characteristics - A product characteristic for  which reasonably anticipated variation could significantly affect the  products safety or its compliance with government regulations and is likely  to significantly affect customer satisfaction.','description':'关键产品特性——指该性能的合理预期偏差会对产品的安全性、符合国家规范或法规以及用户的满意产生极大的影响。'},
{'simpleName':'KPH','fullName':'Kilometers per Hour','description':'公里/小时'},
{'simpleName':'KPI','fullName':'Key Performance Indicator','description':'关键绩效指标'},
{'simpleName':'LAN','fullName':'Local Area Network - A compunication net formed by  interconnections of various computers, peripheral equipments and databases  within an local area. It is always used to link personal computers and  workstation in an office or a plant so as to share resource(eg.printer) and  exchange information.','description':'局域网——是在一个局部的地理范围内,将各种计算机、外围设备、数据库等互相连接起来组成的计算机通信网。常被用于连接公司办公室或工厂里的个人计算机和工作站，以便共享资源（如打印机）和交换信息。'},
{'simpleName':'LAT','fullName':'Lot  Acceptance Testing','description':'批量可接受试验'},
{'simpleName':'LBC','fullName':'Laser beam cutting','description':'激光切割'},
{'simpleName':'LBW','fullName':'Laser beam welding','description':'激光焊'},
{'simpleName':'LCL','fullName':'Lower Control Limit','description':'下控制限'},
{'simpleName':'LCR','fullName':'Lean Capacity Rate','description':'正常生产能力'},
{'simpleName':'LDT','fullName':'Launch Deployment Team','description':'信息技术中启动部署团队'},
{'simpleName':'Lead  Time','fullName':'Lead Time - The duration from confirming order to product  delivery.','description':'准备时间——定单确认至交货的时间。'},
{'simpleName':'LEPC','fullName':'Local Emergency Planning Committee','description':'本地应急情况编制委员会'},
{'simpleName':'LEV','fullName':'Low Emissions Vehicle','description':'低排放车'},
{'simpleName':'LH','fullName':'Left Hand','description':'左手'},
{'simpleName':'LIFO','fullName':'Last in first out - One of the inventory counting principles  often used in western countries, it allows the enterprise adds the cost of  inventory last into sales cost first, and so the sales cost is close  to maket value while the price','description':'后进先出——这是常用于西方国家存货计价核算的原则。允许企业为了减少风险，把后入库的存货先进入销售成本。这样在物价上升时，使销货成本更接近于现行成本。'},
{'simpleName':'LIN','fullName':'Local Interconnect Network','description':'局域互联网络'},
{'simpleName':'LMC','fullName':'Least Material Condition','description':'最小量材料条件'},
{'simpleName':'LPA','fullName':'Layered Process Audit - Layered Process Audits (LPA) are a  system of audits performed by multiple levels of management. Key process  characteristics are audited frequently to verify process  conformance.','description':'分层审核——分层过程审核(LPA)是由多个管理层进行的系统审核。对'},
{'simpleName':'LRR','fullName':'Launch Readiness Report','description':'投产准备报告'},
{'simpleName':'LSL','fullName':'Lower Size Limit','description':'规格下限——一个与CPK（过程能力指数）相关的概念，表示的是样本数据在规格范围内的允许最小值，它与规格上限之差的绝对值既是规'},
{'simpleName':'LTA','fullName':'Long Term Agreement','description':'长期降价计划'},
{'simpleName':'LTL','fullName':'Long Term Lease','description':'长期的协议'},
{'simpleName':'LVDT','fullName':'Linear Variable Differential Transformer','description':'线性可变差动变压器，属于直线位移传感器'},
{'simpleName':'MA','fullName':'Math Matching','description':'数模匹配'},
{'simpleName':'MARS','fullName':'Measurement Analysis and Reporting Systems','description':'测量分析和报告系统'},
{'simpleName':'MB','fullName':'Match Body','description':'车身匹配'},
{'simpleName':'MBOM','fullName':'Manufacture Bill of Material','description':'制造物料清单'},
{'simpleName':'MC','fullName':'Matching Activity','description':'匹配性评估活动'},
{'simpleName':'MCR','fullName':'Maximum Capacity Rate','description':'最大生产能力'},
{'simpleName':'MDDR/DMR','fullName':'Material Defective Data Report','description':'缺陷产品数据报告'},
{'simpleName':'ME','fullName':'Manufacturing Engineer','description':'制造工程师'},
{'simpleName':'MEQ','fullName':'Manufacturing Engineering Quality Standard - The goal of MEQ is  to achieve zero defect, 100 percent efficiency  within thirty days after SOP.','description':'制造工程质量标准——MEQ的目标是0－100－30，即在开始生产的三十天内达到零缺陷和百分之一百效率。'},
{'simpleName':'MES','fullName':'Manufacture Executive System','description':'制造执行系统'},
{'simpleName':'MI','fullName':'Measure Index','description':'尺寸符合率'},
{'simpleName':'Milestone','fullName':'Milestone - The deadline we must finish the related job.','description':'时间节点——我们必须完成相关工作的时间期限。'},
{'simpleName':'MIS','fullName':'Management Information System - Ergonomic system which can  provide the information service for the management decision-making,  establishes with the systemic ideology,take the computer as the basic  information processing method,and take the modern communication equipmeny as  basical','description':'管理信息系统——用系统思想建立起来的，以电子计算机为基本信息处理手段，以现代通讯设备为比本传输工具，且能为管理角色提供信息服务的人际系统。'},
{'simpleName':'Misc.','fullName':'Miscellaneous expenses/Petty - Miscellaneous payout that is not  on plan.','description':'零星费用——不纳入报告计划的零散开销费用。'},
{'simpleName':'MMC','fullName':'Maximum Material Condition','description':'最大量材料条件'},
{'simpleName':'MMS','fullName':'Materials Management System - A system aim to accurately  reflects all material suppliers and components/material data.','description':'材料管理系统——用于精确反映所用材料供应商和零件/材料数据的系统。'},
{'simpleName':'MOS','fullName':'Manufacture Operation System - Describe the processes used for  product manufacturing in BOS.','description':'生产运作系统——BOS中描述产品制造使用的流程。'},
{'simpleName':'MPD','fullName':'Measurement Points Drawing','description':'测点图'},
{'simpleName':'MPG','fullName':'Miles per Gallon','description':'每加仑英里数'},
{'simpleName':'MPH','fullName':'Miles per Hour','description':'每小时英里数'},
{'simpleName':'MPS','fullName':'Master Productin Schedule','description':'主生产计划'},
{'simpleName':'MPV','fullName':'Multi Purpose Vehicle','description':'多用途车'},
{'simpleName':'MQA','fullName':'Manufacture Quality Assurance','description':'制造品质保证'},
{'simpleName':'MQC','fullName':'Manufacturing Quality Control','description':'制造质量控制'},
{'simpleName':'MQR','fullName':'Material Quality Review - Quality Management actions taken due  to supplier product quality problems.','description':'物料质量评审——由于供应商产生的质量问题而采取的质量管理行动'},
{'simpleName':'MRD','fullName':'Material Receipt Date','description':'物料到货时间'},
{'simpleName':'MRF','fullName':'Manufacturing Readiness Review','description':'制造准备工作评审'},
{'simpleName':'MRO','fullName':'Maintenance, Repair and Operations','description':'维护，维修和操作'},
{'simpleName':'MRP','fullName':'Material Requirements Planning - Establishing and reviewing scheduling parameters for supplied components/materials.Communicating  accurate and timely material requirements to each material supplier.','description':'物料需求计划——对供给的零件/材料建立和回顾时序安排参数。对每个材料供应商提供准确的信息和及时的材料要求'},
{'simpleName':'MSA','fullName':'Measurement Systems Analysis - The analysis to a complete  process used to obtain measurements.','description':'测量系统分析——通过对获得测量结果的整个过程进行分析和评定,以选择适用的测量系统。'},
{'simpleName':'MSDS','fullName':'Material Safety Data Sheet - Recorded all those information  relating to the material or product to make them to be used correctly and  safely. Those information includes physical and chemical characters, fire and  explosion protection, Health and saftey, leak and  disposal, sepecial caution and so on.','description':'物料安全数据表——用来描述某中材料或产品的各项信息以确保其被正确安全地使用。信息一般包括其物理和化学性质、防爆防火、健康安全信息、泄漏和废弃处置以及和特殊警告防护信息等。'},
{'simpleName':'MSO','fullName':'Manufacturing Sign-Off','description':'制造签发'},
{'simpleName':'MTTR','fullName':'Mean Time To Repair','description':'平均修复时间（常用设备参数之一）'},
{'simpleName':'MY','fullName':'Model Year - The model year during which the program will  launch.','description':'车型年——在车型年中项目启动。'},
{'simpleName':'MY','fullName':'Model Year','description':'产品年'},
{'simpleName':'N/A','fullName':'Not Applicable','description':'不适用'},
{'simpleName':'NA','fullName':'North America','description':'北美'},
{'simpleName':'NC','fullName':'Numerically Controlled','description':'数控'},
{'simpleName':'NCAP','fullName':'New Car Assessment Program','description':'欧洲新车评估测试'},
{'simpleName':'NDT','fullName':'Non destructive Testing','description':'非破坏性试验和评估'},
{'simpleName':'NG','fullName':'No Good - A term used in Japan.','description':'不好——一日本术语。'},
{'simpleName':'NI','fullName':'National Instrument','description':'美国国家仪器公司，公司名称，主要业务为数据测试设备'},
{'simpleName':'NPV','fullName':'Net Present Value - return an investment based on a discount  rate and a  sense of future payment (negative values) and  income (positive values)','description':'净现值——将投资期间每年的投资支出与投资后的收益的净额，按照符合客观的现值率计算出(净流入或流出的)净现值。'},
{'simpleName':'NS','fullName':'Not Sale','description':'新产品试制非销售阶段'},
{'simpleName':'NVA','fullName':'Non Value Added','description':'非增值'},
{'simpleName':'NVH','fullName':'Noise Vibration and Harshness','description':'噪声，振动与不平顺性'},
{'simpleName':'OCS','fullName':'Occupant Control Sensor','description':'用于座椅是否被坐着的控制传感器'},
{'simpleName':'ODS','fullName':'Operator Description Sheets - Operation description sheet is  the document which tell how to do something with in details.It tells you the  way and requirement which must be done of certain  position,job or activity.','description':'作业指导书——作业指导文件是详细规定某项活动如何进行的文件。主要针对某个特定的岗位、工作或活动规定完成此项工作或活动必须达到的要求和方法。'},
{'simpleName':'OEE','fullName':'Overall Equipment Effectiveness','description':'设备综合效率'},
{'simpleName':'OEM','fullName':'Original Equipment Manufacturer - The roiginal equipment  manufacturer is the one which has its own production or own  productive technology and sometime buy the service of other company to finsh  its production.','description':'原始设备制造厂/主机厂——  设备制造商（OEM）是指拥有自己的产品或产品理念，但有时会为了开发和/或制造这些产品而购买某些服务的公司。'},
{'simpleName':'OHSAS','fullName':'Occupational Health and Safety Assessment Series - To manage  all occupational safety and health risk relating to business, which includes  plan, implement, achieve, audit and maintain the organization, planning  acitvity, responsiblity, pratices, procedure, process and  resource for the OHS policy.','description':'职业健康安全管理评价体系——组织全部管理体系中专门管理与其业务相关的职业安全卫生风险的部分，包括制定、实施、实现、评审和保持职业安全卫生方针所需的组织机构、规划活动、职责、惯例、程序、过程和资源。'},
{'simpleName':'OIL','fullName':'Open Issue List','description':'开口问题清单'},
{'simpleName':'Organization  Chart','fullName':'Organization Chart - The chart descript the realationship of  the clerks, departments and groups.','description':'组织机构图——表示人员，部门，群组关系的图表。'},
{'simpleName':'OSHA','fullName':'Occupational Safety & Health Administration','description':'职业安全和健康管理'},
{'simpleName':'OTD','fullName':'On Time Delivery','description':'及时供货'},
{'simpleName':'OTS','fullName':'Off Tooling Sample - OTS parts are made out of production dies  with production tooling fixtures and production checking fixtures. It is  assembled at the selected local supplier and bench test validated. It should  have same localized content as SORP.The parts could utilize simulated  production processes to manufacture. Production machine and  production line rate are','description':'工装样件——指采用生产用模具、检夹具，在当地制造并经台架试验合格的零部件；其国产化率应与正式生产件相同，但可以采用模拟生产工艺、不用生产用的机床设备、不按生产节拍。'},
{'simpleName':'PA','fullName':'Programe Approve','description':'项目批准'},
{'simpleName':'PA6','fullName':'Polyamide-6','description':'聚酰胺6或尼龙6'},
{'simpleName':'PAA','fullName':'Production Action Authorization','description':'生产行动授权'},
{'simpleName':'PARETO','fullName':'A kind of chart','description':'Pareto图，排列图，按事件发生的频率排序而成'},
{'simpleName':'PBX','fullName':'Private Branch Exchange - It is a telephone system within an  enterprise that switches calls between enterprise users on local  lines while allowing all users to share a certain number of external phone  lines.','description':'用户级交换机——即公司内部使用的电话业务网络，一种公司内部的电话系统，能够交换公司内线电话，同时容许所有用户共享几根外线。'},
{'simpleName':'PC&L','fullName':'Production Control & Logistics Dept.','description':'生产控制与物流部（上海通用物流部门）'},
{'simpleName':'PCB','fullName':'Printd Circuit Board','description':'印刷电路板'},
{'simpleName':'PCBA','fullName':'Printed Circuit Board Assembly','description':'印刷电路板组件'},
{'simpleName':'PCI','fullName':'Peripheral Component Interconnect - PCI is an interconnection  system between a microprocessor and attached devices in which expansion slot  are spaced closely for high speed operation.','description':'周边元件扩展接口——PCI是微处理器同附属设备的一种连接系统，这'},
{'simpleName':'PCMCIA','fullName':'Personal Computer Member Card Internet Association - It is an industry group to promote standards for a credit card-size memory or I/O  device that would fit into a personal computer, usually a notebook or laptop  computer. Probably the most common example of a PCMCIA card is the 28.8  Kbps modem for notebook computers.','description':'个人计算机存储卡国际协会——一个工业组织，致力于促进一种可插入个人电脑，通常是笔记本电脑的，信用卡大小的内存或I/O设备的标准化。最常用的PCMCIA卡可能就是笔记本电脑用的28.8K的modem。'},
{'simpleName':'PCP','fullName':'Process Control Plan','description':'过程控制计划'},
{'simpleName':'PCPA','fullName':'Process Control Plan Audit','description':'过程控制计划审核'},
{'simpleName':'PCR','fullName':'1. Product Cost Request','description':'产品成本申请'},
{'simpleName':'PCS','fullName':'Pieces','description':'块、件、片等'},
{'simpleName':'PD-1','fullName':'PD-1 (Project Definition)','description':'方案定义'},
{'simpleName':'PD-2','fullName':'PD-2 (Engineering Cost Analysis)','description':'工程成本分析'},
{'simpleName':'PDA','fullName':'1. Physical Defination Analysis','description':'物理特性分析'},
{'simpleName':'PDCA','fullName':'Plan Do Check Act - Previding a progressive measure to a  process, do it, check the result and take a suitable action to  improve it.','description':'计划-实施-检查-行动循环——一个以科学方法为基础的改善循环。对 一个过程提出改善方案，实施这个方案，评测结果，然后再采取适当'},
{'simpleName':'PDF','fullName':'1. Portable Document Format','description':'一种文件格式'},
{'simpleName':'PDFSS','fullName':'Product Development for Six Sigma - The utilization of  statistical methods and tools to predict and improve qualtiy before building  prototypes, and then verifying that quality with pilots,  pre-production and production units.','description':'产品开发六西格玛——使用统计方法和工具在制造样品前来预计和改善质量，然后以小批量试生产和生产件来确认其质量。'},
{'simpleName':'PDI','fullName':'Pre-Delivery Inspection','description':'发运前检查'},
{'simpleName':'PDM','fullName':'Product Data Management - PDM systems are used within companies to organize, access and manage information related to its products.PDM system  serve all the people who create or need timely access to accurate  product information in design, engineering and  manufacturing.','description':'产品数据管理——用于组织、获得和管理产品相关信息的系统，可以及时服务于设计、工程和制造相关人员创立或是获得产品信息。'},
{'simpleName':'PDS','fullName':'1. Production Development System','description':'产品开发系统'},
{'simpleName':'PE','fullName':'Product Engineering','description':'产品工程'},
{'simpleName':'PEIL','fullName':'Potential Environmental Issues List - A list contains any  potential ergonomic','description':'潜在环境问题清单——包含一个项目中所有潜在人机工程问题的清单'},
{'simpleName':'PET','fullName':'1. Program Executive Team','description':'项目执行小组'},
{'simpleName':'PF&D','fullName':'Personal Fatigue & Delays','description':'个人，疲劳和延迟'},
{'simpleName':'PFD','fullName':'Process Flow Diagram','description':'过程流程图'},
{'simpleName':'PFEP','fullName':'Plan for Every Part','description':'单一零件清单'},
{'simpleName':'PFMEA','fullName':'Process Failure Mode and Effects Analysis - Is a document used  to identify  potential failure modes for the process.','description':'过程的潜在失效模式分析——用于确认过程潜在失效模式的文件'},
{'simpleName':'PHIL','fullName':'Potential Hazards Issues List','description':'潜在安全问题清单'},
{'simpleName':'PI','fullName':'Process  Index','description':'过程能力符合指数'},
{'simpleName':'PIFF','fullName':'Program Initiation Feasibility Form','description':'项目初始可行性分析报告'},
{'simpleName':'PKR','fullName':'Program Knowledge Review','description':'项目知识评审'},
{'simpleName':'PLC','fullName':'Programmable Logic Controller','description':'可编程的逻辑控制器'},
{'simpleName':'PLM','fullName':'Product Lifecycle Management','description':'产品生命周期管理'},
{'simpleName':'PLP','fullName':'Program Launch Process','description':'项目投产流程'},
{'simpleName':'Plt','fullName':'Plant','description':'工厂/车间'},
{'simpleName':'Plt  Mgr','fullName':'Plant Manager','description':'工厂经理'},
{'simpleName':'PLUS','fullName':'Product Launch System - Describe the steps for product or  process','description':'产品投产系统——BOS中描述产品或过程开发的步骤。'},
{'simpleName':'PM','fullName':'1. Preventative Maintenance - Maintain instrument or equipment  periodical before it comes to   malfunction to insure it works properly.','description':'预防性维修——在设备发生故障前定期的保养以保证设备的正常运行。'},
{'simpleName':'PMP','fullName':'Product Management Plan','description':'生产管制计划'},
{'simpleName':'PN','fullName':'Part Number - The incode to indicate the part.','description':'零件号——用以表示识别零件的。'},
{'simpleName':'PO','fullName':'Purchase Order - A purchase agreement in form of sheet with  supplier.','description':'采购订单——与供应商之间达成的一种书面化的采购协议。'},
{'simpleName':'PODS','fullName':'Passanger  Oppenancy Detection System','description':'乘客是否坐着的探测系统'},
{'simpleName':'Poka  Yoke','fullName':'Error proofing device','description':'防错'},
{'simpleName':'POM','fullName':'Polyoxymethylene','description':'聚甲醛，一种没有侧链，高密度，高结晶性的线型聚合物'},
{'simpleName':'Pp','fullName':'Preliminary Process Performance, Performance Index of Process','description':'初始过程性能——过程性能指数，定义为不考虑过程有无偏移时，容差范围除以过程性能'},
{'simpleName':'PPA','fullName':'Product Planning Approval','description':'产品规划批准'},
{'simpleName':'PPAP','fullName':'Production Part Approval Process - To determine if all customer  engineering design record and specification requirements are properly  understood by the supplier and that the process has the potential to produce  product meeting these requirements during an actual production  run at quoted production','description':'生产零件批准过程——用来确定客户工程设计记录和规格要求被供应商恰当地理解；同时，在实际生产中，在要求的生产速率下，工艺具备制造达标产品的潜力。'},
{'simpleName':'PPC','fullName':'Production Plan Control','description':'生产计划控制'},
{'simpleName':'PPE','fullName':'Personal Protective Equipment - It is a protection equipment  that can protect labour from accidents.','description':'个人防护设备——指劳动者在生产过程中为免遭或减轻事故伤害或职业危害的所配备的一种防护性装备。'},
{'simpleName':'PPH','fullName':'Problems per Hundred','description':'每百辆车的问题'},
{'simpleName':'PPHR','fullName':'Past Problem History Roadmap','description':'以往问题历史路径图'},
{'simpleName':'Ppk','fullName':'Preliminary Process Capability - Short-term study conducted to  obtain early information on the performance of new or revised  processes .','description':'初始过程能力——开展短期研究来获得有关新或更改的工艺表现的早期信息。'},
{'simpleName':'PPM','fullName':'Parts per Million - number/1000000.','description':'（产品缺陷）百万分率——数值/1000000得出的比例。'},
{'simpleName':'PPSC','fullName':'Potential  Product Safety Concern - Any potential  safety/compliance issue','description':'潜在产品安全关注——任何潜在的安全/符合性问题'},
{'simpleName':'PQPT','fullName':'Production Quality Plan Team','description':'产品质量策划小组'},
{'simpleName':'PR','fullName':'Performance Review','description':'绩效评估'},
{'simpleName':'PR&R','fullName':'Problem Reporting and Resolution','description':'问题报告和决议（通用汽车问题解决的一种形式）'},
{'simpleName':'Process  Flow Chart','fullName':'Process Flow Chart - Visual approach to describing and  developing sequential or related work activities. It provides both a means  of communication and analysis for planning,  development activities and','description':'工艺流程图——用视觉图表来描述和开发相关工作活动，以提供策划、开发活动和制造过程交流和分析方法。'},
{'simpleName':'Prototype','fullName':'Prototype - Parts are to be made to authorized drawings,  templates, models, and/or other engineering design records, using specified  materials. Prototype Samples manufacturing conditions could be different from  regular  production requyirements, such as soft tooling,  simplified fixture,...etc.','description':'手工样品——按认可的图纸、样板、模型和/或其它工程设计资料，使用指定的材料制造的样件。样件可按某些不同于正规生产要求的方法制造，如使用软模具，简易夹具等。样件用于认证设计。'},
{'simpleName':'PRP','fullName':'Product Realization Plan','description':'产品实现计划'},
{'simpleName':'PRTS','fullName':'Problem Resolution & Tracking System','description':'问题解决和跟踪系统'},
{'simpleName':'PSA','fullName':'Potential Supplier Assessment','description':'潜在供应商评估'},
{'simpleName':'PSD','fullName':'Problem Solving Document - Systematic problem sloving method  form of','description':'问题解决报告 - 问题系统解决方法表式，如8D。'},
{'simpleName':'PSO','fullName':'Process Sign-off - PSO originated from Daimler-Chysler is a  process audit on people, machine, material, method, enviroment, process,  software, fixture and tooling and so on under the condition of supplier  highest daily production speed.','description':'过程签发（工艺认证）——源于戴姆勒克莱斯勒，是对供应商实施的最高日生产节拍下的生产工艺审核。包括人、机、料、法、环、程序、软件和工装等。'},
{'simpleName':'PSW','fullName':'Parts Submission Warrant','description':'零件提交保证书'},
{'simpleName':'PTR','fullName':'Production Trail Run','description':'生产试运行——在产品SOP之前对产品的工艺及生产设备和生产人员的'},
{'simpleName':'PV','fullName':'Product Validation - Analysis performed to verify  conformance to all specification requirements when product is constructed  using production processes, equipment and tool','description':'生产验证——进行分析来确认所有技术规格要求的一致性，测试用产品应使用批量生产过程、设备和工装来制造。'},
{'simpleName':'PVS','fullName':'Produktions Versuchs Serie','description':'批量试生产（德文）——大众汽车集团通用缩略语。'},
{'simpleName':'PXI','fullName':'PCI extensions for Instrumentation','description':'面向仪器系统的PCI扩展，是一种由NI公司发布的坚固的基于PC的测'},
{'simpleName':'QA','fullName':'Quality Assurance','description':'质量保证'},
{'simpleName':'QAD','fullName':'An EPR System Company Name','description':'一个EPR软件公司名称'},
{'simpleName':'QAP','fullName':'Quality Assurance Planning','description':'质量保证计划'},
{'simpleName':'QC','fullName':'Quality Control','description':'质量控制'},
{'simpleName':'QCC','fullName':'Quality Control Circles','description':'质量圈'},
{'simpleName':'QCO','fullName':'Quality Change Over','description':'快速切换'},
{'simpleName':'QCOS','fullName':'Quality Control Operation Sheets','description':'质量记录表'},
{'simpleName':'QE','fullName':'Quality Engineer','description':'质量工程师'},
{'simpleName':'QFD','fullName':'Quality Function Deployment - A structured method in which  customer requirements are translated into appropriate technical requirements  for each stage of product, development and production.','description':'质量功能展开——是一种结构化的方法，用这种方法把顾客的要求转化为产品每一个阶段(开发和生产)适当的技术要求。'},
{'simpleName':'QM','fullName':'Quality Management','description':'质量管理'},
{'simpleName':'QOS','fullName':'Quality Operation System','description':'质量运作系统'},
{'simpleName':'QPN','fullName':'Qualifizierungs Programm Neuteile','description':'新零件质量提升计划（德文）'},
{'simpleName':'QS','fullName':'Quality System','description':'质量体系'},
{'simpleName':'QS-9000','fullName':'QS-9000 - Quality system requiements of American big three','description':'美国三大汽车公司质量体系标准'},
{'simpleName':'QSA','fullName':'Quality System Assessment - A manual which is used for  idenifying the system is compliance with the QS9000 system  requirements or not.','description':'质量系统评估——用于确定体系是否符合QS9000质量体系的要求。'},
{'simpleName':'QSB','fullName':'Quality System Basic Audit','description':'质量体系基础评审(通用）'},
{'simpleName':'QSR','fullName':'Quality System Requirements','description':'质量体系要求'},
{'simpleName':'QSTP','fullName':'Quality, Service, Technic, Price','description':'质量,服务,技术,价格'},
{'simpleName':'Qty','fullName':'Quantity','description':'数量'},
{'simpleName':'QUEST','fullName':'Quality Excellence and Systems Training','description':'质量卓越和体系培训'},
{'simpleName':'QWS','fullName':'Quotation Work Sheet','description':'报价工作表'},
{'simpleName':'R&R','fullName':'Repeatablility And Reproductivity - Repeatability is the  variation in measurements obtained with one gage when used several times by  one appraiser while measuring a characeristic on one part. Reproducibility is  the variation in the average of the measurements made by different  appraisers using the same gage when measuring a  characteristic on one part.','description':'重复性和再现性——重复性是由一个评价人，采用一种测量仪器，多次测量同一零件的同一特性时获得的测量值变差。再现性是由不同的评价人，采用相同的测量仪器，测量同一零件的同一特性时测量平均值的变差。'},
{'simpleName':'R@R','fullName':'Run at Rate - It’s to run according to the client’s requirement  rate, so the equipoise production can come true.','description':'节拍生产——按照客户的要货节拍进行生产，以保持各工序和产品生产的节奏性，实现均衡生产。'},
{'simpleName':'RAB','fullName':'Registrar Accreditation Board','description':'注册认证局'},
{'simpleName':'RAM','fullName':'Random Access Memory','description':'随机存取存储器'},
{'simpleName':'Ramp-up','fullName':'Ramp-up - The time the program takes to get to normal speed.','description':'爬坡——增量或渐进， 即无须等待时间，直接执行或实现。'},
{'simpleName':'RCRA','fullName':'Resource Conservation & Recovery Act','description':'资源保持和恢复'},
{'simpleName':'RDC','fullName':'1. Regional Distribution Center','description':'区域配送中心'},
{'simpleName':'RFID','fullName':'Radio Frequency Identification','description':'无线射频识别技术'},
{'simpleName':'RFP','fullName':'Request for Proposal','description':'建议请求'},
{'simpleName':'RFQ','fullName':'Request for Quotation - The tabulation used to inquire the  price of production or material.','description':'报价需求表——用来询问产品或者原料价格的表格。'},
{'simpleName':'RH','fullName':'Right Hand','description':'右手'},
{'simpleName':'RMS','fullName':'Resource Management System','description':'资源管理系统'},
{'simpleName':'ROA','fullName':'Return on Assets - EBIT/NOA','description':'资产回报/盈利率——公式：息税前利润除以全部资产的百分率'},
{'simpleName':'ROHS','fullName':'the Restriction of the use of certain Hazardous Substances','description':'电气、电子设备中限制使用某些有害物质指令'},
{'simpleName':'ROS','fullName':'Return on Sales - EBIT/SALES','description':'销售回报率——公式：息税前利润除以年销售总额的百分率'},
{'simpleName':'RPM','fullName':'Revolutions per Minute','description':'每分钟转速'},
{'simpleName':'RPN','fullName':'Risk Priority Number - RPN is the product of Severity(S),  Occurrence(O), and Detection(D) rankings.','description':'风险顺序数——风险顺序数(RPN)是严重度数(S)，频度数(O)和不易探 测度数(D)的乘积。'},
{'simpleName':'RPPM','fullName':'Reject Parts per Million - The number of production that  customer reject to accept and this number is calculated per  million.','description':'客户拒收百万分率——每百万件产品中客户拒绝接受的数目。'},
{'simpleName':'RPSR','fullName':'Robust Problem Solving Report','description':'根本问题解决报告'},
{'simpleName':'RSB','fullName':'Rear Seat Back - Rear Row Seat Back','description':'后座椅靠背——后排座椅靠背。'},
{'simpleName':'RSO','fullName':'Requirements Sign-Off','description':'需求签发'},
{'simpleName':'RSW','fullName':'Resistance Spot Welding','description':'点焊'},
{'simpleName':'RTTR','fullName':'Resource Tool Tracking Report','description':'设备资源跟踪报告'},
{'simpleName':'RTY','fullName':'Rolled Throughput Yield - The computation of RTY provides a  method to identify opportunities for improvement and to characterize the process steps which will unveil the hidden factory.','description':'滚动产出率——RTY的计算提供了一种识别改进机会的方法和突显出能揭露隐藏工厂的步骤。'},
{'simpleName':'S&R','fullName':'Squeak & Rattle','description':'车辆行驶时摩擦、振动噪音，泛指异响'},
{'simpleName':'S.W.I.P.E.','fullName':'Standard, Workpiece, Instrument, Person/Procedure, Environment','description':'标准，零件，仪器，人/程序，环境(测量系统分析误差模型）'},
{'simpleName':'S/N','fullName':'Signal-to-Noise Ratio','description':'信噪比'},
{'simpleName':'SAB','fullName':'Side Airbag - when crash occur, the air bag that set in the  outboard of driver seat is used to protect the trunk of occupant.','description':'侧面安全气囊——靠门一侧安装的由传感器、微处理器、气体发生器和气囊等部件组成侧面安全气囊。'},
{'simpleName':'SAIC','fullName':'Shanghai Automotive Industry Corp. Group','description':'上海汽车工业（集团）总公司'},
{'simpleName':'SBR','fullName':' Seat Belt Reminder','description':'座椅安全带提醒装置'},
{'simpleName':'SC','fullName':'1. Significant Characteristics - Any design characteristic for which reasonably anticipated variation is likely to significantly affect  customer satisfaction with a product such as its fit, function, mounting or  appearance, or the ability to process or build the product.','description':'1. 重要特性——任何由于其可能的变化而显著地影响客户对产品的满意度，例如配合、功能、安装和外观、工艺能力和产品制造能力。'},
{'simpleName':'SCA','fullName':'SCA Schucker','description':'公司名称，SCA苏格，主要业务为涂胶系统'},
{'simpleName':'SCMS','fullName':'Supply Chain Management System','description':'供应链管理系统'},
{'simpleName':'SCU','fullName':'Sunroof Control Unit','description':'天窗控制单元'},
{'simpleName':'SDE','fullName':'Supplier Development Engineer','description':'供应商开发工程师'},
{'simpleName':'SDS','fullName':'Supplier Delivery System','description':'供应商发运系统'},
{'simpleName':'SDT','fullName':'Simultaneous Development Team - Select members from different  funtional departments to implement project development  together.','description':'同步开发小组——来自不同部门的成员组成的团队，来实施项目开发 。'},
{'simpleName':'SE','fullName':'Self Exinguishing','description':'自行熄灭'},
{'simpleName':'SFCP','fullName':'Shop Floor Control Plan','description':'工厂控制计划'},
{'simpleName':'SGM','fullName':'Shanghai General Motor - SGM is a joint venture established in  1997 by American GM   Auto and  SAIC.','description':'上海通用汽车有限公司——上海通用是一家美国通用汽车和上汽于1997年共同投资兴建的汽车公司。'},
{'simpleName':'SIL','fullName':'Single Issues List','description':'单一问题清单，最严重质量问题的最终汇总和整体状态的跟踪'},
{'simpleName':'SKD','fullName':'Semi Knocked Down','description':'部分散件——国际贸易中，特别是在国际汽车贸易中，整车出口国的汽车公司把成品予以拆散，而以半成品或零部件的方式出口，再由进口厂商在所在国以自行装配方式完成整车成品并进行销售'},
{'simpleName':'SMART','fullName':'Specific, Measurable, Attainable, Results-oriented, Time-bound','description':'具体的，可衡量，可达到的，以结果为导向的，有时间限定的（目标'},
{'simpleName':'SMC','fullName':'SAIC Motor Passenger Vehicle Co.','description':'上海汽车股份有限公司乘用车分公司'},
{'simpleName':'SMED','fullName':'Single Minute Exchange of Die','description':'快速换模；快速换产'},
{'simpleName':'SMRR','fullName':'Supplier Material Rejection Report','description':'供应商物料拒收报告'},
{'simpleName':'SMS','fullName':'Strategy Management System','description':'战略管理系统'},
{'simpleName':'SMSO','fullName':'Supplier Material System Operation','description':'供应商物料运作系统'},
{'simpleName':'SMT','fullName':'System Management Team','description':'采购、工程、SQE联合工作小组'},
{'simpleName':'SMTC','fullName':'SAIC Motor Technical Center','description':'上海汽车股份有限公司技术中心'},
{'simpleName':'SMTE','fullName':'Subject Matter Technical Expert','description':'主题技术专家'},
{'simpleName':'SOP','fullName':'Start of Production - Initiation of volume production to  support customer assembly operations; equal to Job','description':'生产开始(正式/批量)——支持客户总装作业的开始批量生产，等同于“工作1”。'},
{'simpleName':'SOR','fullName':'Statement of Requirement','description':'合同要求'},
{'simpleName':'SOS','fullName':'Standardized Operation Sheets','description':'标准作业单'},
{'simpleName':'SOW','fullName':'Statement of Work - Overall description of the services. SVW  names it as','description':'工作指南——客户服务的完整描述，大众称为LH。'},
{'simpleName':'SPA','fullName':'Shipping Priority Audit','description':'发运前检查'},
{'simpleName':'SPC','fullName':'Special Processe Characteristic','description':'过程特殊特性（如关键、主要、重要、重点）是这样一种产品特性：对合理预测的变差，会明显影响产品安全性或政府标准或法规的一致性，或者会显著影响顾客对产品的满意程度。'},
{'simpleName':'SPCC','fullName':'Spill Prevention, Control and Countermeasures','description':'预防，控制和对策'},
{'simpleName':'SPPM','fullName':'Supplier PPM - The number of supplier parts be rejected per  million.','description':'供应商拒收数 - 供应商零件每百万件被拒收的数量。'},
{'simpleName':'SPQRC','fullName':'Safety, People, Quality, Responsiveness, Cost','description':'五大目标'},
{'simpleName':'SPR','fullName':'Supplier Performance Rating','description':'供应商业绩表现'},
{'simpleName':'SPSO','fullName':'Supplier Process Sign-off - A "Quality Systems and manufacturing','description':'供应商过程签发——是我们在进行文件评估时对质量系统和制造准备'},
{'simpleName':'SQA','fullName':'Supplier Quality Assurance','description':'供应商质量保证'},
{'simpleName':'SQC','fullName':'Statistical Quality Control','description':'统计质量管理'},
{'simpleName':'SQE','fullName':'Supplier Quality Engineer','description':'供应商质量工程师'},
{'simpleName':'SRR','fullName':'Systems Requirements Request','description':'系统要求申请'},
{'simpleName':'SSO','fullName':'Product Safety Sign-Off','description':'产品安全签发'},
{'simpleName':'SSOW','fullName':'Supplier Statement of Work - This document outlines the program','description':'供应商工作指南——此文件概括了与指定项目的开发和生产相关的项'},
{'simpleName':'STO','fullName':'Seat Trim Outline Drawing','description':'座椅轮阔图'},
{'simpleName':'SUV','fullName':'Sports Utility Vehicle','description':'运动型多功能车'},
{'simpleName':'SV','fullName':'Supplier Visualization','description':'供应链可视化系统'},
{'simpleName':'SVW','fullName':'Shanghai Volkswagen - SVW is a joint venture established in  19985 by  German Vlokswagen  and   SAIC.','description':'上海大众汽车有限公司——上海大众是一家德国大众汽车和上汽于1985年共同投资兴建的汽车公司。'},
{'simpleName':'SW','fullName':'Steering Wheel','description':'方向盘'},
{'simpleName':'TA','fullName':'Technical Assessment Procedure for Potential Supplier','description':'供应商技术评估'},
{'simpleName':'TAKT','fullName':'Takt Time','description':'生产节拍时间'},
{'simpleName':'TBD','fullName':'To Be Determined - It is used to espress the state of some  project in form.','description':'待决定——在制作表格的时候经常用来表示某项工作所处的状态。'},
{'simpleName':'TCP/IP','fullName':'Transmission  Control Protocol/Internet Protocol - it is the  basic communication protocol of the internet. It can also be used as a communications protocol in a private network.','description':'传输控制协议/互联网协议——互联网上基本的通讯协议，也可用作专用网的通讯协议。'},
{'simpleName':'TDI','fullName':'Toluene - 2, 4 - Diisocyanate','description':'发泡化学原料'},
{'simpleName':'TDS','fullName':'Technical Data Sheet','description':'技术数据表，包含产品的技术参数和性能的相关信息'},
{'simpleName':'TGR','fullName':'Things Go Right - Past success experience','description':'运行情况良好——过去的成功经验'},
{'simpleName':'TGW','fullName':'Things Go Wrong - Past failure experience','description':'运行情况不良——过去的失败经验'},
{'simpleName':'TIR','fullName':'Test Issues Resolution','description':'试车/装车问题'},
{'simpleName':'TLTS','fullName':'Top Load Top Slider','description':''},
{'simpleName':'TOC','fullName':'Theory of Constraints','description':'限制理论'},
{'simpleName':'TOD','fullName':'Term of Delivery','description':'交付期限，交付条件'},
{'simpleName':'TPM','fullName':'Total Productive Maintenance - A system to achieve zero  machine-related defects and zero machine breakdowns.','description':'全员生产性维护——一种达到设备相关故障为零和设备失效为零的体系。'},
{'simpleName':'TPQ','fullName':'Threshold  Planning Quantity','description':'计划的临界值'},
{'simpleName':'TQC','fullName':'Total Quality Control','description':'全面质量控制'},
{'simpleName':'TQM','fullName':'Total Quality Management','description':'全面质量管理'},
{'simpleName':'TR','fullName':'Team Rally - Team Rally is a yearly worldwide competition held  by Johnson Controls as well as a meeting where every team can demonstrate  their achievement and share their successful experience with others and is  awarded for their accomplishment. Our company holds such  a competition annually.','description':'团队集会——团队集会是江森每年举行一次全球范围内的比赛，是各个团队表演其取得的成绩，与他人分享其经验并借此表彰团队所取得的成就的聚会。本公司每年度举行一次这样的比赛。'},
{'simpleName':'TRI','fullName':'Temporary Rework Instruction','description':'临时返工指导书'},
{'simpleName':'TTF','fullName':'Time To Fire (for pre-tensioners, air bags, etc.)','description':'点火时刻（用于预紧器，气囊等）'},
{'simpleName':'TV','fullName':'Total Variation','description':'总变差'},
{'simpleName':'TVR','fullName':'Tool Verification Report','description':'模具确认报告'},
{'simpleName':'TVS','fullName':'Tilt Vent Slider','description':''},
{'simpleName':'UAI','fullName':'Use As It','description':'可用'},
{'simpleName':'UCL','fullName':'Upper Control Limit','description':'上控制限'},
{'simpleName':'ULP','fullName':'United States Logistic Platform','description':'美国物流平台'},
{'simpleName':'UOM','fullName':'Unit of Measure','description':'计量单位'},
{'simpleName':'UPC','fullName':'Universal Product Code  - Sort and number those import and export products or materials to meet the requirement of custom  management including taxation and report during the international commerce,','description':'通用产品代码——指国际贸易中，为便于对不同货物的征税、统计等海关管理，对进出口货物、材料进行分类编码。'},
{'simpleName':'US','fullName':'Ultra Sound','description':'超声（波）'},
{'simpleName':'USB','fullName':'Universal Serial Bus - It is a plug-and-play interface between a  computer and add-on devices (such as joysticks, keyboards, scanners, and  printers). With USB, a new device can be added to your computer without  having to add an adapter card or even having to turn the computer  off.','description':'通用串行总线 -  一种计算机同外设（如音响，游戏杆，键盘，电话，扫描仪，打印机）之间的即插即用接口。使用USB,新的外设可直接连上电脑而无须使用适配卡，甚至无须关机。'},
{'simpleName':'USL','fullName':'Upper Size Limit','description':'规格上限'},
{'simpleName':'UV','fullName':'Ultraviolet','description':'紫外线'},
{'simpleName':'VDA','fullName':'Verband Deutschen  Automobilindustrie','description':'德国汽车工业联合会（德文）'},
{'simpleName':'VDA6.1','fullName':'VDA6.1 German automotive quality system requirements.','description':'德国汽车工业质量体系标准。'},
{'simpleName':'VDR','fullName':'Voltage Dependent Resistor','description':'压敏电阻'},
{'simpleName':'VIN','fullName':'Vehicle Identification Number','description':'车辆识别号码'},
{'simpleName':'VIS','fullName':'Vehicle Information System','description':'虚拟信息系统'},
{'simpleName':'VMI','fullName':'Vendor  Managed Inventory','description':'供应商管理库存'},
{'simpleName':'VOC','fullName':'Voice of Customer','description':'客户呼声'},
{'simpleName':'VP','fullName':'Verification Prototype','description':'样件验证，福特APQP术语'},
{'simpleName':'VPN','fullName':'Virtual Private Network - It is a private data network that makes use of the public telecommunication infrastructure, maintaining privacy  through the use of a tunneling protocol and security procedures. A virtual  private network  can be contrasted with  a system of owned or leased lines that can only be used by one company. The  idea of the VPN is to give the company the same capabilities at much lower cost by using the  shared public infrastructure','description':'虚拟专用网——利用公网设施通过使用隧道协议和安全机制维持其专用性，故称作虚拟专用网。对比那种一个公司购买或租用的并且独用的专用线路系统而言，它可以使得公司以少的多的价格获得相同的性能。'},
{'simpleName':'VSA','fullName':'Variation Simulation Analysis','description':'变更模拟分析'},
{'simpleName':'VSO','fullName':'Verification Sign-Off','description':'验证签发'},
{'simpleName':'WAN','fullName':'Wide Area Network - It is data traffic network that covers large  aera, with comparatively slow transmitted speed, and aimed  to data communications.','description':'广域网——是指覆盖范围广、传输速率相对较低、以数据通信为主要目的的数据通信网。'},
{'simpleName':'WAP','fullName':'Wireless Application Protocol -   It is a specification for a set of communication protocols to  standardize the way that wireless devices, such as cellular telephones and  radio transceivers, can be used for Internet access,including e-mail, the World Wide Web and  newsgroups.','description':'无线应用协议——用来规范无线设备访问因特网,包括电子邮件，万维网，新闻组等服务的一组协议。'},
{'simpleName':'WBBA','fullName':'Worldwide Benchmarking and Business Analysis','description':'全球基准和商业分析'},
{'simpleName':'WBS','fullName':'Work Breakdown Structure','description':'工作分解表'},
{'simpleName':'WDM','fullName':'Weight Drop Machine','description':'落重设备－－校准用于气囊控制的座椅重量传感器'},
{'simpleName':'WDPV','fullName':'Weighted Discrepancies per Vehicle','description':'平均每辆车不符合项与权重乘积的总和（平均每辆车扣分值）'},
{'simpleName':'WF','fullName':'Work Flow','description':'工作流'},
{'simpleName':'WH','fullName':'Warehouse','description':'仓库'},
{'simpleName':'WI','fullName':'Working Instruction','description':'操作规程'},
{'simpleName':'WIP','fullName':'Work in Process','description':'在制品'},
{'simpleName':'WVP','fullName':'Water Vapor Permeability','description':'水蒸汽渗透性'},
{'simpleName':'WVT','fullName':'Water Vapor Transmission','description':'水蒸气透过性；透湿性'},
{'simpleName':'XML','fullName':'Extensible Markup Language - It is a flexible way to create  common information formats and share both the format  and the data on the World Wide Web, intranets, and elsewhere.','description':'扩展标识语言——为创建通用信息格式以及在万维网、内部网上共享格式和数据提供的一种灵活的方式。'},
{'simpleName':'YTD','fullName':'Year to Date','description':'年初到今日'},
{'simpleName':'ZD','fullName':'Zero Defects','description':'零缺陷'}
]